apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: prompt
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: prompt
    dag:
      tasks:
      - name: t1
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: '{{workflow.parameters.prompt}}'
      - name: t2
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: '{{workflow.parameters.prompt}}'
      - name: t3
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: '{{workflow.parameters.prompt}}'
      - name: t4
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: '{{workflow.parameters.prompt}}'
      - name: t5
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: '{{workflow.parameters.prompt}}'
      - name: t6
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: '{{workflow.parameters.prompt}}'
      - name: t7
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: '{{workflow.parameters.prompt}}'
      - name: t8
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: '{{workflow.parameters.prompt}}'
  - name: tti-sketching-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url:       # You should specify the endpoint URL here
      successCondition: response.statusCode == 200
