apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti-animation-art
        arguments:
          parameters:
          - name: prompt
            value: Generate an animated image of a high school boy in Japan.
      - name: t2
        template: tti-animation-art
        arguments:
          parameters:
          - name: prompt
            value: Generate an animated image of a high school girl in Japan.

      - name: t3
        template: tti-animation-art
        arguments:
          parameters:
          - name: prompt
            value: '{{tasks.t1.outputs.result}} {{tasks.t2.outputs.result}} Enhance
              the animated image of the high school boy.'
        dependencies: [t1, t2]
      - name: t4
        template: tti-futurArt
        arguments:
          parameters:
          - name: prompt
            value: '{{tasks.t1.outputs.result}} {{tasks.t2.outputs.result}} Enhance
              the animated image of the high school girl.'
        dependencies: [t1, t2]

      - name: t5
        template: image-resizing
        arguments:
          parameters:
          - name: width
            value: 500
          - name: height
            value: 800
          - name: file
            value: '{{tasks.t3.outputs.result}}'
        dependencies: [t3, t4]
      - name: t6
        template: image-resizing
        arguments:
          parameters:
          - name: width
            value: 500
          - name: height
            value: 800
          - name: file
            value: '{{tasks.t4.outputs.result}}'
        dependencies: [t3, t4]

      - name: t7
        template: image-format-converter
        arguments:
          parameters:
          - name: output_format
            value: png
          - name: file
            value: '{{tasks.t5.outputs.result}}'
        dependencies: [t5, t6]
      - name: t8
        template: image-format-converter
        arguments:
          parameters:
          - name: output_format
            value: jpeg
          - name: file
            value: '{{tasks.t6.outputs.result}}'
        dependencies: [t5, t6]

  - name: tti-animation-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://tti-animation-art.url/anime_image
      successCondition: response.statusCode == 200

  - name: tti-futurArt
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://tti-futurArt.url/futuristic_image
      successCondition: response.statusCode == 200

  - name: image-resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://image-resizing.url/resize
      successCondition: response.statusCode == 200

  - name: image-format-converter
    inputs:
      parameters:
      - name: output_format
      - name: file
    http:
      method: POST
      url: http://image-format-converter.url/convert
      successCondition: response.statusCode == 200
