apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti_Charcoal_Art
        arguments:
          parameters:
          - name: prompt
            value: '{{workflow.parameters.prompt}}'
        dependencies: []

      - name: t2
        template: tti_Pastel_Art
        arguments:
          parameters:
          - name: prompt
            value: '{{workflow.parameters.prompt}}'
        dependencies: []

      - name: t3
        template: tti_Painting_Art
        arguments:
          parameters:
          - name: prompt
            value: '{{workflow.parameters.prompt}}'
        dependencies: []

      - name: t4
        template: tti_Ukiyo_e_Art
        arguments:
          parameters:
          - name: prompt
            value: '{{workflow.parameters.prompt}}'
        dependencies: []

      - name: t5
        template: tti_Charcoal_Art
        arguments:
          parameters:
          - name: prompt
            value: '{{workflow.parameters.prompt}}'
        dependencies: [t1, t2, t3, t4]

      - name: t6
        template: tti_Pastel_Art
        arguments:
          parameters:
          - name: prompt
            value: '{{workflow.parameters.prompt}}'
        dependencies: [t1, t2, t3, t4]

      - name: t7
        template: tti_Painting_Art
        arguments:
          parameters:
          - name: prompt
            value: '{{workflow.parameters.prompt}}'
        dependencies: [t1, t2, t3, t4]

      - name: t8
        template: tti_Ukiyo_e_Art
        arguments:
          parameters:
          - name: prompt
            value: '{{workflow.parameters.prompt}}'
        dependencies: [t1, t2, t3, t4]

  - name: tti_Charcoal_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://path_to_your_charcoal_art_endpoint
      successCondition: response.statusCode == 200

  - name: tti_Pastel_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://path_to_your_pastel_art_endpoint
      successCondition: response.statusCode == 200

  - name: tti_Painting_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://path_to_your_painting_art_endpoint
      successCondition: response.statusCode == 200

  - name: tti_Ukiyo_e_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://path_to_your_ukiyo_e_art_endpoint
      successCondition: response.statusCode == 200
