apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti_Sketching_Art_1900s
        arguments:
          parameters:
          - name: prompt
            value: Technological advancements of computers in the early 1900s
        dependencies: []
      - name: t2
        template: tti_Sketching_Art_1950s
        arguments:
          parameters:
          - name: prompt
            value: Technological advancements of computers in the 1950s
        dependencies: []
      - name: t3
        template: tti_Sketching_Art_2020s
        arguments:
          parameters:
          - name: prompt
            value: Technological advancements of computers in the 2020s
        dependencies: []
      - name: t4
        template: convert_image_to_png
        dependencies: [t1]
        arguments:
          parameters:
          - name: prompt
            value: '{{tasks.t1.outputs}}'
      - name: t5
        template: convert_image_to_png
        dependencies: [t2]
        arguments:
          parameters:
          - name: prompt
            value: '{{tasks.t2.outputs}}'
      - name: t6
        template: convert_image_to_png
        dependencies: [t3]
        arguments:
          parameters:
          - name: prompt
            value: '{{tasks.t3.outputs}}'
      - name: t7
        template: send_email
        dependencies: [t4, t5, t6]
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t4.outputs}}'
          - name: file
            value: '{{tasks.t5.outputs}}'
          - name: file
            value: '{{tasks.t6.outputs}}'

  - name: tti_Sketching_Art_1900s
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://tti_sketching_art/1900s
      successCondition: response.statusCode == 200

  - name: tti_Sketching_Art_1950s
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://tti_sketching_art/1950s
      successCondition: response.statusCode == 200

  - name: tti_Sketching_Art_2020s
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://tti_sketching_art/2020s
      successCondition: response.statusCode == 200

  - name: convert_image_to_png
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://convert_image_to_png
      successCondition: response.statusCode == 200

  - name: email_image
    inputs:
      parameters:
      - name: image_1900s
      - name: image_1950s
      - name: image_2020s
    http:
      method: POST
      url: http://email_image
      successCondition: response.statusCode == 200
