apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti_Graffiti_Art
        arguments:
          parameters:
          - name: prompt
            value: urban jungle
  - name: tti_Graffiti_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: /generate_grafiti_image/
      successCondition: response.statusCode == 200
