apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: width
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: width
    dag:
      tasks:
      - name: t1
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art image of an old library.
        dependencies: []
  - name: tti_Sketching_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://<url-to-the-implementation-endpoint>/generate_sketching_image/
      successCondition: response.statusCode == 200
