apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti_mosaic_art
        arguments:
          parameters:
          - name: prompt
            value: Create a digital art image of a serene mountain landscape during
              sunrise.
      - name: t2
        dependencies: [t1]
        template: tti_pastel_art
        arguments:
          parameters:
          - name: prompt
            value: Create a pastel art image of the same mountain landscape during
              sunset.
      - name: t3
        dependencies: [t2]
        template: tti_sketching_art
        arguments:
          parameters:
          - name: prompt
            value: Create a sketching art image of the mountain landscape at night
              with a starry sky.
      - name: t4
        dependencies: [t3]
        template: image_resizing
        arguments:
          parameters:
          - name: width
            value: 1920
          - name: height
            value: 1080
          - name: file
            value: '{{tasks.t3.outputs.art}}'
      - name: t5
        dependencies: [t4]
        template: image_enhancement
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t4.outputs.resized_image}}'
      - name: t6
        dependencies: [t5]
        template: tti_mosaic_art
        arguments:
          parameters:
          - name: prompt
            value: Email the final digital art image of the serene mountain landscape
              during sunrise to the client for review.

  - name: tti_mosaic_art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://<tti_mosaic_art_service>/generate_mosaic_image/
      successCondition: status == 200

  - name: tti_pastel_art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://<tti_pastel_art_service>/generate_pastel_image/
      successCondition: status == 200

  - name: tti_sketching_art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://<tti_sketching_art_service>/generate_sketching_image/
      successCondition: status == 200

  - name: image_resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://<image_resizing_service>/resize_image/
      successCondition: status == 200

  - name: image_enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://<image_enhancement_service>/image_enhance/
      successCondition: status == 200
