apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti-pastel-art
        arguments:
          parameters:
          - name: prompt
            value: Create a pastel art image of a sunset over the ocean.
  - name: tti-pastel-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://path-to-your-fastapi-service/generate_pastel_image/
      headers:
        Content-Type: application/json
      body: '{"prompt": "{{inputs.parameters.prompt}}"}'
      successCondition: response.statusCode == 200
      timeoutSeconds: 300
