apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti-charcoal-art
        arguments:
          parameters:
          - name: prompt
            value: Generate a charcoal art image of a serene forest.
        dependencies: []
  - name: tti-charcoal-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://example.com/generate_charcoal_image/    # Replace with the correct URL
      body: '{"prompt": "{{inputs.parameters.prompt}}"}'
      headers:
        Accept: application/json
        Content-Type: application/json
      successCondition: response.statusCode == 200
