apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: A bustling marketplace
        dependencies: []
      - name: t2
        template: image_to_pdf_conversion
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t1.outputs.art_image}}'
        dependencies:
        - t1
  - name: tti_Sketching_Art
    inputs:
      parameters:
      - name: prompt
        description: The 'prompt' parameter is a user-provided textual prompt in string
          format that serves as the input for generating artistic sketching images.
          It is essential for guiding the AI model to create visually striking sketching
          art style images based on the user's creative input.
    outputs:
      parameters:
      - name: art_image
        description: A high-quality sketching art style image depicting a bustling
          marketplace, saved in PNG format.
    http:
      method: POST
      url: http://example.com/generate_sketching_image/
      successCondition: response.statusCode == 200
  - name: image_to_pdf_conversion
    inputs:
      parameters:
      - name: file
        description: An image file in supported format (.JPEG .PNG .GIF .BMP .TIFF
          .PBM .PGM .PPM)
    outputs:
      parameters:
      - name: pdf_document
        description: The API will generate a PDF document containing the sketching
          art image of 'A bustling marketplace' converted from the uploaded image
          file.
    http:
      method: POST
      url: http://example.com/convert_to_pdf/
      successCondition: response.statusCode == 200
