apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti-pastel-art
        arguments:
          parameters:
          - name: prompt
            value: A peaceful beach at sunrise
        dependencies: []
      - name: t2
        template: image-enhancement
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t1.outputs.result}}'
        dependencies: [t1]

  - name: tti-pastel-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://pastel-art-api/generate_pastel_image/
      body:
        parameters:
        - name: prompt
          value: '{{inputs.parameters.prompt}}'
      headers:
        Content-Type: application/json
      successCondition: response.statusCode == 200
      output:
        artifacts:
        - name: result
          path: /tmp/generated_art.png

  - name: image-enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://image-enhance-api/image_enhance/
      body:
        parameters:
        - name: file
          value: '{{inputs.parameters.file}}'
      headers:
        Content-Type: multipart/form-data
      successCondition: response.statusCode == 200
      output:
        artifacts:
        - name: result
          path: /tmp/enhanced_image.jpg
