apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti-charcoal-art
        arguments:
          parameters:
          - name: prompt
            value: Create a charcoal art image of a New York landscape in 1990.
      - name: t2
        dependencies: [t1]
        template: tti-charcoal-art
        arguments:
          parameters:
          - name: prompt
            value: '{{tasks.t1.outputs.result}}'
      - name: t3
        dependencies: [t2]
        template: image-resizing
        arguments:
          parameters:
          - name: width
            value: 800
          - name: height
            value: 600
          - name: file
            value: '{{tasks.t2.outputs.result}}'
      - name: t4
        dependencies: [t3]
        template: image-enhancement
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t3.outputs.result}}'
      - name: t5
        dependencies: [t4]
        template: email-image
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t4.outputs.result}}'
          - name: email
            value: colleague@example.com
  - name: tti-charcoal-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://example.com/generate_charcoal_image/
      body:
        prompt: '{{inputs.parameters.prompt}}'
      successCondition: response.statusCode == 200
  - name: image-resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://example.com/resize_image/
      body:
        width: '{{inputs.parameters.width}}'
        height: '{{inputs.parameters.height}}'
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200
  - name: image-enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://example.com/image_enhance/
      body:
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200
  - name: email-image
    inputs:
      parameters:
      - name: file
      - name: email
    http:
      method: POST
      url: http://example.com/send_email/
      body:
        file: '{{inputs.parameters.file}}'
        email: '{{inputs.parameters.email}}'
      successCondition: response.statusCode == 200
