apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: width
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: width
    dag:
      tasks:
      - name: t1
        template: tti_Futuristic_Art
        arguments:
          parameters:
          - name: prompt
            value: A futuristic cityscape at night.
      - name: t2
        template: image_to_pdf_conversion
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t1.outputs.result}}'
        dependencies: [t1]
      - name: t3
        template: Image_Resizing
        arguments:
          parameters:
          - name: width
            value: 1920
          - name: height
            value: 1080
          - name: file
            value: '{{tasks.t2.outputs.result}}'
        dependencies: [t2]
      - name: t4
        template: Image_Enhancement
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t3.outputs.result}}'
        dependencies: [t3]
      - name: t5
        template: send_email
        arguments:
          parameters:
          - name: sender_address
            value: example_sender@example.com
          - name: receiver_address
            value: example_receiver@example.com
          - name: message_text
            value: Please find attached the enhanced image of the futuristic cityscape
              at night.
          - name: message_subject
            value: Enhanced Image of Futuristic Cityscape
          - name: file
            value: '{{tasks.t4.outputs.result}}'
        dependencies: [t4]

  - name: tti_Futuristic_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your-api-endpoint/tti-Futuristic-Art
      body:
        prompt: '{{inputs.parameters.prompt}}'
      successCondition: response.statusCode == 200

  - name: image_to_pdf_conversion
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://your-api-endpoint/image-to-pdf-conversion
      body:
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200

  - name: Image_Resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://your-api-endpoint/image-resizing
      body:
        width: '{{inputs.parameters.width}}'
        height: '{{inputs.parameters.height}}'
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200

  - name: Image_Enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://your-api-endpoint/image-enhancement
      body:
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200

  - name: send_email
    inputs:
      parameters:
      - name: sender_address
      - name: receiver_address
      - name: message_text
      - name: message_subject
      - name: file
    http:
      method: POST
      url: http://your-api-endpoint/send-email
      body:
        sender_address: '{{inputs.parameters.sender_address}}'
        receiver_address: '{{inputs.parameters.receiver_address}}'
        message_text: '{{inputs.parameters.message_text}}'
        message_subject: '{{inputs.parameters.message_subject}}'
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200
