apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: prompt
    - name: prompt
    - name: prompt
    - name: prompt
    - name: prompt
    - name: file
    - name: prompt
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: prompt
      - name: prompt
      - name: prompt
      - name: prompt
      - name: prompt
      - name: file
      - name: prompt
    dag:
      tasks:
      - name: t1
        template: tti-mosaic-art
        arguments:
          parameters:
          - name: prompt
            value: '{{ inputs.parameters.prompt }}'
        dependencies: []
      - name: t2
        template: tti-pastel-art
        arguments:
          parameters:
          - name: prompt
            value: '{{ inputs.parameters.prompt }}'
        dependencies: []
      - name: t3
        template: tti-graffiti-art
        arguments:
          parameters:
          - name: prompt
            value: '{{ inputs.parameters.prompt }}'
        dependencies: []
      - name: t4
        template: tti-mosaic-art
        arguments:
          parameters:
          - name: prompt
            value: '{{ inputs.parameters.prompt }}'
        dependencies:
        - t1
        - t2
        - t3
      - name: t5
        template: tti-mosaic-art
        arguments:
          parameters:
          - name: prompt
            value: '{{ inputs.parameters.prompt }}'
        dependencies:
        - t1
        - t2
        - t3
      - name: t6
        template: image-enhancement
        arguments:
          parameters:
          - name: file
            value: '{{ inputs.parameters.file }}'
        dependencies:
        - t1
        - t2
        - t3
      - name: t7
        template: tti-mosaic-art
        arguments:
          parameters:
          - name: prompt
            value: '{{ inputs.parameters.prompt }}'
        dependencies:
        - t4
        - t5
        - t6
  - name: tti-mosaic-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url:
      successCondition: response.statusCode == 200
  - name: tti-pastel-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url:
      successCondition: response.statusCode == 200
  - name: tti-graffiti-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url:
      successCondition: response.statusCode == 200
  - name: image-enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url:
      successCondition: response.statusCode == 200
