apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti_charcoal_art
        arguments:
          parameters:
          - name: prompt
            value: Create a charcoal art image of a New York landscape in 1990.
      - name: t2
        template: tti_charcoal_art
        dependencies:
        - t1
        arguments:
          parameters:
          - name: prompt
            value: Convert the charcoal art image of the New York landscape in 1990
              to PNG format.
      - name: t3
        template: image_resizing
        dependencies:
        - t2
        arguments:
          parameters:
          - name: width
            value: 800
          - name: height
            value: 600
          - name: file
            value: '{{{{ tasks.t2.outputs.result }}}}'
      - name: t4
        template: image_enhancement
        dependencies:
        - t3
        arguments:
          parameters:
          - name: file
            value: '{{{{ tasks.t3.outputs.result }}}}'

      - name: t5
        template: send_enhanced_image
        dependencies:
        - t4
        arguments:
          parameters:
          - name: file
            value: '{{{{ tasks.t4.outputs.result }}}}'

  - name: tti_charcoal_art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: <add your API endpoint here>
      headers:
        Content-Type: application/json
      body:
        prompt: '{{inputs.parameters.prompt}}'
      successCondition: response.statusCode == 200
      output:
        result: '{{response.body}}'

  - name: image_resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: <add your API endpoint here>
      headers:
        Content-Type: application/octet-stream
      body:
        width: '{{inputs.parameters.width}}'
        height: '{{inputs.parameters.height}}'
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200
      output:
        result: '{{response.body}}'

  - name: image_enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: <add your API endpoint here>
      headers:
        Content-Type: application/octet-stream
      body:
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200
      output:
        result: '{{response.body}}'

  - name: send_enhanced_image
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: <add your API endpoint here>
      headers:
        Content-Type: application/octet-stream
      body:
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200
      output:
        result: '{{response.body}}'
