apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: prompt
      value: Bustling marketplace
    - name: width
      value: 800
    - name: height
      value: 600
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: prompt
      - name: width
      - name: height
    dag:
      tasks:
      - name: t0
        template: tti-Sketching-Art
        arguments:
          parameters:
          - name: prompt
            value: '{{inputs.parameters.prompt}}'

      - name: t1
        template: image-resizing
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t0.outputs.result}}'
          - name: width
            value: '{{inputs.parameters.width}}'
          - name: height
            value: '{{inputs.parameters.height}}'
        dependencies: [t0]

  - name: tti-Sketching-Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://fake-api.com/generate_sketching_image/
      headers:
        Content-Type: application/json
      body: |
        {
          "prompt": "{{inputs.parameters.prompt}}"
        }
      successCondition: response.statusCode == 200
      output:
        result: '{{response.body}}'

  - name: image-resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://fake-api.com/resize_image/
      headers:
        Content-Type: multipart/form-data
      body: |
        {
          "width": "{{inputs.parameters.width}}",
          "height": "{{inputs.parameters.height}}",
          "file": "{{inputs.parameters.file}}"
        }
      successCondition: response.statusCode == 200
      output:
        result: '{{response.body}}'
