apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: width
    - name: height
    - name: file
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    dag:
      tasks:
      - name: t1
        template: tti-futuristic-art
        arguments:
          parameters:
          - name: prompt
            value: A futuristic cityscape
        dependencies: []
      - name: t2
        template: tti-pastel-art
        arguments:
          parameters:
          - name: prompt
            value: '{{tasks.t1.outputs.parameters["prompt"]}}'
        dependencies: [t1]
      - name: t3
        template: image-resizing
        arguments:
          parameters:
          - name: width
            value: '{{inputs.parameters.width}}'
          - name: height
            value: '{{inputs.parameters.height}}'
          - name: file
            value: '{{tasks.t2.outputs.parameters["file"]}}'
        dependencies: [t2]

  - name: tti-futuristic-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your-futuristic-art-api-url/generate_futuristic_image/
      successCondition: response.statusCode == 200
      headers:
        Content-Type: application/json
      body:
        prompt: '{{inputs.parameters.prompt}}'

  - name: tti-pastel-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your-pastel-art-api-url/generate_pastel_image/
      successCondition: response.statusCode == 200
      headers:
        Content-Type: application/json
      body:
        prompt: '{{inputs.parameters.prompt}}'

  - name: image-resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://your-image-resizing-api-url/resize_image/
      successCondition: response.statusCode == 200
      headers:
        Content-Type: multipart/form-data
      form:
        width: '{{inputs.parameters.width}}'
        height: '{{inputs.parameters.height}}'
        file: '{{inputs.parameters.file}}'
