apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Create a sketch of a castle surrounded by a dense forest.
      - name: t2
        dependencies: [t1]
        template: Image_Resizing
        arguments:
          parameters:
          - name: width
            value: 1280
          - name: height
            value: 720
          - name: file
            value: '{{tasks.t1.outputs.artifact}}'
      - name: t3
        dependencies: [t2]
        template: Image_Enhancement
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t2.outputs.artifact}}'
      - name: t4
        dependencies: [t3]
        template: image_to_pdf_conversion
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t3.outputs.artifact}}'
      - name: t5
        dependencies: [t4]
        template: send_email
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t4.outputs.artifact}}'
  - name: tti_Sketching_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: <API_URL_FOR_tti_Sketching_Art>
      successCondition: response.statusCode == 200

  - name: Image_Resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: <API_URL_FOR_Image_Resizing>
      headers:
        Content-Type: multipart/form-data
      formData:
        width: '{{inputs.parameters.width}}'
        height: '{{inputs.parameters.height}}'
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200

  - name: Image_Enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: <API_URL_FOR_Image_Enhancement>
      headers:
        Content-Type: multipart/form-data
      formData:
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200

  - name: image_to_pdf_conversion
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: <API_URL_FOR_image_to_pdf_conversion>
      headers:
        Content-Type: multipart/form-data
      formData:
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200

  - name: send_email
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: <API_URL_FOR_send_email>
      headers:
        Content-Type: multipart/form-data
      formData:
        file: '{{inputs.parameters.file}}'
        to: colleague@example.com
        subject: Enhanced Sketch PDF
        body: Find the attached PDF of the enhanced sketch.
      successCondition: response.statusCode == 200
