apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: prompt
      value: Create a pastel art image of a sunset over the ocean.
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: prompt
    dag:
      tasks:
      - name: t1
        template: tti_Pastel_Art
        arguments:
          parameters:
          - name: prompt
            value: '{{inputs.parameters.prompt}}'
        dependencies: []

      - name: t2
        template: Image_Enhancement
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t1.outputs.artifact.result}}'
        dependencies: [t1]

      - name: t3
        template: tti_Pastel_Art
        arguments:
          parameters:
          - name: prompt
            value: '{{tasks.t2.outputs.artifact.result}}'
        dependencies: [t2]

  - name: tti_Pastel_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: <REPLACE_WITH_ACTUAL_URL>/generate_pastel_image/
      headers:
      - name: Content-Type
        value: application/json
      body: |
        {
          "prompt": "{{inputs.parameters.prompt}}"
        }
      successCondition: response.statusCode == 200
      output:
        result: '{{response.artifacts}}'

  - name: Image_Enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: <REPLACE_WITH_ACTUAL_URL>/image_enhance/
      headers:
      - name: Content-Type
        value: multipart/form-data
      body: |
        {
          "file": "{{inputs.parameters.file}}"
        }
      successCondition: response.statusCode == 200
      output:
        result: '{{response.artifacts}}'
