apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: width
    - name: height
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: width
      - name: height
    dag:
      tasks:
      - name: t0
        template: tti_Sketching_Art_0
        arguments:
          parameters:
          - name: prompt
            value: Create a sketching art image of a bustling marketplace.
      - name: t1
        template: tti_Sketching_Art_1
        arguments:
          parameters:
          - name: prompt
            value: Convert the sketching art image of the bustling marketplace to
              a PNG format.
        dependencies:
        - t0
      - name: t2
        template: Image_Resizing
        arguments:
          parameters:
          - name: width
            value: '{{inputs.parameters.width}}'
          - name: height
            value: '{{inputs.parameters.height}}'
          - name: file
            value: '{{tasks.t1.outputs.result}}'
        dependencies:
        - t1

  - name: tti_Sketching_Art_0
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: <Your_API_URL_0>
      parameters:
        body:
          application/json:
            prompt: '{{inputs.parameters.prompt}}'
      successCondition: response.statusCode == 200

  - name: tti_Sketching_Art_1
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: <Your_API_URL_1>
      parameters:
        body:
          application/json:
            prompt: '{{inputs.parameters.prompt}}'
      successCondition: response.statusCode == 200

  - name: Image_Resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: <Your_API_URL_2>
      parameters:
        body:
          multipart/form-data:
            width: '{{inputs.parameters.width}}'
            height: '{{inputs.parameters.height}}'
            file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200
