apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti_Painting_Art
        arguments:
          parameters:
          - name: prompt
            value: Create a digital art image of a serene mountain landscape during
              sunrise.
      - name: t2
        template: tti_Pastel_Art
        arguments:
          parameters:
          - name: prompt
            value: Create a pastel art image of the same mountain landscape during
              sunset.
        dependencies: [t1]
      - name: t3
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Create a sketching art image of the mountain landscape at night
              with a starry sky.
        dependencies: [t1]

      - name: t4
        template: Image_Resizing
        arguments:
          parameters:
          - name: width
            value: '1920'
          - name: height
            value: '1080'
          - name: file
            value: '{{tasks.t1.outputs.result}}'
        dependencies: [t1]
      - name: t5
        template: Image_Enhancement
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t4.outputs.result}}'
        dependencies: [t4]
      - name: t6
        template: tti_Mosaic_Art
        arguments:
          parameters:
          - name: prompt
            value: Create a digital art image of a serene mountain landscape during
              sunrise.
        dependencies: [t5]

  - name: tti_Painting_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://example.com/generate_painting_image/
      parameters:
        body:
          prompt: '{{inputs.parameters.prompt}}'
      successCondition: response.statusCode == 200

  - name: tti_Pastel_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://example.com/generate_pastel_image/
      parameters:
        body:
          prompt: '{{inputs.parameters.prompt}}'
      successCondition: response.statusCode == 200

  - name: tti_Sketching_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://example.com/generate_sketching_image/
      parameters:
        body:
          prompt: '{{inputs.parameters.prompt}}'
      successCondition: response.statusCode == 200

  - name: Image_Resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://example.com/resize_image/
      parameters:
        body:
          width: '{{inputs.parameters.width}}'
          height: '{{inputs.parameters.height}}'
          file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200

  - name: Image_Enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://example.com/image_enhance/
      parameters:
        body:
          file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200

  - name: tti_Mosaic_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://example.com/generate_mosaic_image/
      parameters:
        body:
          prompt: '{{inputs.parameters.prompt}}'
      successCondition: response.statusCode == 200
