apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: prompt
    - name: width
    - name: height
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: prompt
      - name: width
      - name: height
    dag:
      tasks:
      - name: t1
        template: tti-Graffiti-Art
        arguments:
          parameters:
          - name: prompt
            value: '{{inputs.parameters.prompt}}'
      - name: t2
        template: tti-Mosaic-Art
        arguments:
          parameters:
          - name: prompt
            value: '{{inputs.parameters.prompt}}'
      - name: t3
        template: tti-Ukiyo-e-Art
        arguments:
          parameters:
          - name: prompt
            value: '{{inputs.parameters.prompt}}'
      - name: t4
        dependencies: [t1]
        template: Image-Resizing
        arguments:
          parameters:
          - name: width
            value: '{{inputs.parameters.width}}'
          - name: height
            value: '{{inputs.parameters.height}}'
          - name: file
            value: '{{tasks.t1.outputs.result}}'
      - name: t5
        dependencies: [t2]
        template: Image-Enhancement
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t2.outputs.result}}'
      - name: t6
        dependencies: [t3]
        template: Image-Enhancement
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t3.outputs.result}}'

  - name: tti-Graffiti-Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://<url-to-tti-Graffiti-Art-endpoint>    # replace with actual URL
      json:
        prompt: '{{inputs.parameters.prompt}}'
      successCondition: response.statusCode == 200

  - name: tti-Mosaic-Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://<url-to-tti-Mosaic-Art-endpoint>    # replace with actual URL
      json:
        prompt: '{{inputs.parameters.prompt}}'
      successCondition: response.statusCode == 200

  - name: tti-Ukiyo-e-Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://<url-to-tti-Ukiyo-e-Art-endpoint>    # replace with actual URL
      json:
        prompt: '{{inputs.parameters.prompt}}'
      successCondition: response.statusCode == 200

  - name: Image-Resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://<url-to-Image-Resizing-endpoint>    # replace with actual URL
      json:
        width: '{{inputs.parameters.width}}'
        height: '{{inputs.parameters.height}}'
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200

  - name: Image-Enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://<url-to-Image-Enhancement-endpoint>    # replace with actual URL
      json:
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200
