apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti-animation-art
        arguments:
          parameters:
          - name: prompt
            value: Generate an animated image of a high school boy in Japan.
      - name: t2
        template: tti-animation-art
        arguments:
          parameters:
          - name: prompt
            value: Generate an animated image of a high school girl in Japan.
        dependencies: [t1]
      - name: t3
        template: tti-animation-art
        arguments:
          parameters:
          - name: prompt
            value: Enhance the animated image of the high school boy.
        dependencies: [t2]
      - name: t4
        template: tti-futuristic-art
        arguments:
          parameters:
          - name: prompt
            value: Enhance the animated image of the high school girl.
        dependencies: [t3]
      - name: t5
        template: image-resizing
        arguments:
          parameters:
          - name: width
            value: '500'
          - name: height
            value: '800'
          - name: file
            value: '{{tasks.t2.outputs.artifacts.image}}'
        dependencies: [t2]
      - name: t6
        template: image-resizing
        arguments:
          parameters:
          - name: width
            value: '500'
          - name: height
            value: '800'
          - name: file
            value: '{{tasks.t3.outputs.artifacts.image}}'
        dependencies: [t3]
      - name: t7
        template: image-format-converter
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t3.outputs.artifacts.image}}'
          - name: output_format
            value: PNG
        dependencies: [t3]
      - name: t8
        template: image-format-converter
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t6.outputs.artifacts.image}}'
          - name: output_format
            value: JPEG
        dependencies: [t7]

  - name: tti-animation-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://image-generation.api/tti-animation-art
      body:
        prompt: '{{inputs.parameters.prompt}}'
      successCondition: response.statusCode == 200

  - name: tti-futuristic-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://image-generation.api/tti-futuristic-art
      body:
        prompt: '{{inputs.parameters.prompt}}'
      successCondition: response.statusCode == 200

  - name: image-resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://image-resizing.api/resize_image
      body:
        width: '{{inputs.parameters.width}}'
        height: '{{inputs.parameters.height}}'
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200

  - name: image-format-converter
    inputs:
      parameters:
      - name: file
      - name: output_format
    http:
      method: POST
      url: http://image-conversion.api/convert_image
      body:
        file: '{{inputs.parameters.file}}'
        output_format: '{{inputs.parameters.output_format}}'
      successCondition: response.statusCode == 200
