apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image depicting technological advancements
              of computers in the early 1900s.
      - name: t2
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image depicting technological advancements
              of computers in the 1950s.
        dependencies: [t1]
      - name: t3
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a futuristic art style image depicting technological advancements
              of computers in the 2020s.
        dependencies: [t2]
      - name: t4
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Convert the sketching art style image of the early 1900s to PNG
              format.
        dependencies: [t3]
      - name: t5
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Convert the sketching art style image of the 1950s to PNG format.
        dependencies: [t4]
      - name: t6
        template: tti_Futuristic_Art
        arguments:
          parameters:
          - name: prompt
            value: Convert the futuristic art style image of the 2020s to PNG format.
        dependencies: [t5]
      - name: t7
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Email the PNG format image of the 2020s to the project supervisor.
        dependencies: [t6]

  - name: tti_Sketching_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://example-sketching-art-url  # Replace with the actual URL
      successCondition: response.statusCode == 200

  - name: tti_Futuristic_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://example-futuristic-art-url  # Replace with the actual URL
      successCondition: response.statusCode == 200
