apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti-charcoal-art
        arguments:
          parameters:
          - name: prompt
            value: Create a charcoal art image of a New York landscape in 1990.
      - name: t2
        template: tti-charcoal-art
        arguments:
          parameters:
          - name: prompt
            value: Convert the charcoal art image of the New York landscape in 1990
              to PNG format.
        dependencies: [t1]
      - name: t3
        template: image-resizing
        arguments:
          parameters:
          - name: width
            value: 800
          - name: height
            value: 600
          - name: file
            value: '{{ tasks.t2.outputs.result }}'
        dependencies: [t2]
      - name: t4
        template: image-enhancement
        arguments:
          parameters:
          - name: file
            value: '{{ tasks.t3.outputs.result }}'
        dependencies: [t3]
  - name: tti-charcoal-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: https://yourapi.com/generate_charcoal_image
      headers:
        Content-Type: application/json
      body: '{"prompt": "{{inputs.parameters.prompt}}"}'
      successCondition: response.statusCode == 200


  - name: image-resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: https://yourapi.com/resize_image
      headers:
        Content-Type: application/json
      body: '{"width": "{{inputs.parameters.width}}", "height": "{{inputs.parameters.height}}",
        "file": "{{inputs.parameters.file}}"}'
      successCondition: response.statusCode == 200

  - name: image-enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: https://yourapi.com/enhance_image
      headers:
        Content-Type: application/json
      body: '{"file": "{{inputs.parameters.file}}"}'
      successCondition: response.statusCode == 200
