apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti-Pastel-Art
        arguments:
          parameters:
          - name: prompt
            value: pastel art sunset over the ocean
      - name: t2
        dependencies: [t1]
        template: Convert-to-JPEG
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t1.outputs.result}}'
      - name: t3
        dependencies: [t2]
        template: Image-Resizing
        arguments:
          parameters:
          - name: width
            value: 1024
          - name: height
            value: 768
          - name: file
            value: '{{tasks.t2.outputs.result}}'
      - name: t4
        dependencies: [t3]
        template: Image-Enhancement
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t3.outputs.result}}'
      - name: t5
        dependencies: [t4]
        template: Send-Email
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t4.outputs.result}}'

  - name: tti-Pastel-Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://api.example.com/tti_Pastel_Art
      body:
        parameter: '{{inputs.parameters.prompt}}'
      successCondition: response.statusCode == 200

  - name: Convert-to-JPEG
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://api.example.com/convert-to-jpeg
      body:
        parameter: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200

  - name: Image-Resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://api.example.com/resize_image
      body:
        width: '{{inputs.parameters.width}}'
        height: '{{inputs.parameters.height}}'
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200

  - name: Image-Enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://api.example.com/image_enhance
      body:
        parameter: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200

  - name: Send-Email
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://api.example.com/send_email
      body:
        parameter: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200
