apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: width
    - name: prompt
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: width
      - name: prompt
    dag:
      tasks:
      - name: t1
        template: tti-pastel-art
        arguments:
          parameters:
          - name: prompt
            value: '{{inputs.parameters.prompt}}'
        dependencies: []
      - name: t2
        template: convert-to-jpeg
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t1.outputs.artifact}}'
        dependencies:
        - t1
      - name: t3
        template: image-resizing
        arguments:
          parameters:
          - name: width
            value: '{{inputs.parameters.width}}'
          - name: height
            value: 768
          - name: file
            value: '{{tasks.t2.outputs.artifact}}'
        dependencies:
        - t2
      - name: t4
        template: image-enhancement
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t3.outputs.artifact}}'
        dependencies:
        - t3
      - name: t5
        template: send-email
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t4.outputs.artifact}}'
        dependencies:
        - t4

  - name: tti-pastel-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: /generate_pastel_image
      successCondition: response.statusCode == 200
      body:
        prompt: '{{inputs.parameters.prompt}}'

  - name: convert-to-jpeg
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: /convert_to_jpeg
      successCondition: response.statusCode == 200

  - name: image-resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: /resize_image
      successCondition: response.statusCode == 200
      body:
        width: '{{inputs.parameters.width}}'
        height: '{{inputs.parameters.height}}'
        file: '{{inputs.parameters.file}}'

  - name: image-enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: /image_enhance
      successCondition: response.statusCode == 200
      body:
        file: '{{inputs.parameters.file}}'

  - name: send-email
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: /send_email
      successCondition: response.statusCode == 200
      body:
        file: '{{inputs.parameters.file}}'
