apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: width
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: width
    dag:
      tasks:
      - name: t1
        template: tti_Pastel_Art
        arguments:
          parameters:
          - name: prompt
            value: '{{inputs.parameters.width}}'  # Assuming width parameter is used as the prompt
        dependencies: []
      - name: t2
        template: Image_Enhancement
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t1.outputs.result}}'  # Using the output from t1 as input for t2
        dependencies:
        - t1
      - name: t3
        template: Send_Email
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t2.outputs.result}}'  # Using the output from t2 as input for t3
        dependencies:
        - t2

  - name: tti_Pastel_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://api.pastelart.com/generate    # Replace with actual URL
      successCondition: response.statusCode == 200

  - name: Image_Enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://api.imageenhancement.com/enhance    # Replace with actual URL
      successCondition: response.statusCode == 200

  - name: Send_Email
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://api.sendemail.com/send    # Replace with actual URL
      successCondition: response.statusCode == 200
