apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: width
      value: '800'  # You might want to alter this value as required
    - name: height
      value: '600'  # You might want to alter this value as required
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: width
      - name: height
    dag:
      tasks:
      - name: t1
        template: tti-futuristic-art
        arguments:
          parameters:
          - name: prompt
            value: Imagine a futuristic cityscape with advanced technology and sleek
              architecture.
        dependencies: []

      - name: t2
        template: tti-pastel-art
        arguments:
          parameters:
          - name: prompt
            value: '{{{{ tasks.t1.result }}}}'
        dependencies:
        - t1

      - name: t3
        template: image-resizing
        arguments:
          parameters:
          - name: width
          - name: height
          - name: file
            value: '{{{{ tasks.t2.result }}}}'
        dependencies:
        - t2

  - name: tti-futuristic-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://example.com/generate_futuristic_image    # Replace with actual URL
      headers:
        Content-Type: application/json
      jsonBody: '{"prompt": "{{inputs.parameters.prompt}}"}'
      successCondition: response.statusCode == 200
      output:
        result: /path/to/response/file

  - name: tti-pastel-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://example.com/generate_pastel_image    # Replace with actual URL
      headers:
        Content-Type: application/json
      jsonBody: '{"prompt": "{{inputs.parameters.prompt}}"}'
      successCondition: response.statusCode == 200
      output:
        result: /path/to/response/file

  - name: image-resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://example.com/resize_image    # Replace with actual URL
      headers:
        Content-Type: application/json
      jsonBody: '{"width": "{{inputs.parameters.width}}", "height": "{{inputs.parameters.height}}",
        "file": "{{inputs.parameters.file}}"}'
      successCondition: response.statusCode == 200
      output:
        result: /path/to/response/pdf
