apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters: []
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters: []
    dag:
      tasks:
      - name: t1
        template: tti-charcoal-art
        arguments:
          parameters: []
        dependencies: []
      - name: t2
        template: tti-pastel-art
        arguments:
          parameters: []
        dependencies: []
      - name: t3
        template: tti-painting-art
        arguments:
          parameters: []
        dependencies: []
      - name: t1
        template: tti-ukiyo-e-art
        arguments:
          parameters:
          - name: prompt
            value: '{{ tasks.t3.result }}'
        dependencies: []
      - name: t5
        template: tti-charcoal-art
        arguments:
          parameters: []
        dependencies:
        - t1
        - t2
        - t3
        - t4
      - name: t6
        template: tti-pastel-art
        arguments:
          parameters: []
        dependencies:
        - t1
        - t2
        - t3
        - t4
      - name: t7
        template: tti-painting-art
        arguments:
          parameters: []
        dependencies:
        - t1
        - t2
        - t3
        - t4
      - name: t8
        template: tti-ukiyo-e-art
        arguments:
          parameters: []
        dependencies:
        - t1
        - t2
        - t3
        - t4
  - name: tti-charcoal-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url:
      successCondition: response.statusCode == 200
  - name: tti-pastel-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url:
      successCondition: response.statusCode == 200
  - name: tti-painting-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url:
      successCondition: response.statusCode == 200
  - name: tti-ukiyo-e-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url:
      successCondition: response.statusCode == 200
