apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: width
    - name: height
    - name: email
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: width
      - name: height
      - name: email
    dag:
      - name: t1
        template: tti-pastel-art
        arguments:
          parameters:
          - name: prompt
            value: Create a pastel art image of a sunset over the ocean.
        dependencies: [t1]
      - name: t2
        template: convert-image-to-jpeg
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t1.outputs.result}}'
        dependencies: [t1]
      - name: t3
        template: resize-image
        arguments:
          parameters:
          - name: width
            value: '{{inputs.parameters.width}}'
          - name: height
            value: '{{inputs.parameters.height}}'
          - name: file
            value: '{{tasks.t2.outputs.result}}'
        dependencies: [t2]
      - name: t4
        template: image-enhancement
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t3.outputs.result}}'
        dependencies: [t3]
      - name: t5
        template: send-email
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t4.outputs.result}}'
          - name: email
            value: '{{inputs.parameters.email}}'
        dependencies: [t4]
  - name: tti-pastel-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: https://path.to/api/generate_pastel_image/
      headers:
        Content-Type: application/json
      body: |
        {
          "prompt": "{{inputs.parameters.prompt}}"
        }
      successCondition: response.statusCode == 200
  - name: convert-image-to-jpeg
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: https://path.to/api/convert_to_jpeg/
      headers:
        Content-Type: application/octet-stream
      body: |
        {{inputs.parameters.file}}
      successCondition: response.statusCode == 200
  - name: resize-image
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: https://path.to/api/resize_image/
      headers:
        Content-Type: application/octet-stream
      body: |
        {
          "width": "{{inputs.parameters.width}}",
          "height": "{{inputs.parameters.height}}",
          "file": "{{inputs.parameters.file}}"
        }
      successCondition: response.statusCode == 200
  - name: image-enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: https://path.to/api/image_enhance/
      headers:
        Content-Type: application/octet-stream
      body: |
        {{inputs.parameters.file}}
      successCondition: response.statusCode == 200
  - name: send-email
    inputs:
      parameters:
      - name: file
      - name: email
    http:
      method: POST
      url: https://path.to/api/send_email/
      headers:
        Content-Type: application/json
      body: |
        {
          "file": "{{inputs.parameters.file}}",
          "email": "{{inputs.parameters.email}}"
        }
      successCondition: response.statusCode == 200
