apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Labrador Retriever
      - name: t2
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: German Shepherd
      - name: t3
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Golden Retriever
      - name: t4
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Bulldog
      - name: t5
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Poodle
      - name: t6
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Beagle
      - name: t7
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Rottweiler
      - name: t8
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Dachshund
      - name: t9
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Siberian Husky
      - name: t10
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Shih Tzu
  - name: tti_Sketching_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://localhost:8000/generate_sketching_image
      headers:
        Content-Type: application/json
      body:
        text: |
          {"prompt": "{{inputs.parameters.prompt}}"}    
      successCondition: response.statusCode == 200
