apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti-painting-art
        arguments:
          parameters:
          - name: prompt
            value: Create a digital art image of a serene mountain landscape during
              sunrise.
      - name: t2
        template: tti-pastel-art
        arguments:
          parameters:
          - name: prompt
            value: Create a pastel art image of the same mountain landscape during
              sunset.
        dependencies: [t1]
      - name: t3
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: Create a sketching art image of the mountain landscape at night
              with a starry sky.
        dependencies: [t2]
      - name: t4
        template: image-resizing
        arguments:
          parameters:
          - name: width
            value: 1920
          - name: height
            value: 1080
          - name: file
            value: '{{tasks.t3.outputs.result}}'
        dependencies: [t3]
      - name: t5
        template: image-enhancement
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t4.outputs.result}}'
        dependencies: [t4]
      - name: t6
        template: tti-mosaic-art
        arguments:
          parameters:
          - name: prompt
            value: Email the final digital art image of the serene mountain landscape
              during sunrise to the client for review.
        dependencies: [t5]

  - name: tti-painting-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://path.to.tti-painting-art.com/generate_painting_image/
      body:
        prompt: '{{inputs.parameters.prompt}}'
      successCondition: response.statusCode == 200

  - name: tti-pastel-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://path.to.tti-pastel-art.com/generate_pastel_image/
      body:
        prompt: '{{inputs.parameters.prompt}}'
      successCondition: response.statusCode == 200

  - name: tti-sketching-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://path.to.tti-sketching-art.com/generate_sketching_image/
      body:
        prompt: '{{inputs.parameters.prompt}}'
      successCondition: response.statusCode == 200

  - name: image-resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://path.to.image-resizing.com/resize_image/
      body:
        width: '{{inputs.parameters.width}}'
        height: '{{inputs.parameters.height}}'
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200

  - name: image-enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://path.to.image-enhancement.com/image_enhance/
      body:
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200

  - name: tti-mosaic-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://path.to.tti-mosaic-art.com/generate_mosaic_image/
      body:
        prompt: '{{inputs.parameters.prompt}}'
      successCondition: response.statusCode == 200
