apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: prompt
  templates:
  - name: main
    inputs:
      parameters:
      - name: prompt
    dag:
      tasks:
      - name: t1
        template: tti_Sketching_Art_early_1900s
        arguments:
          parameters:
          - name: prompt
            value: '{{inputs.parameters.prompt}}'
        dependencies: []

      - name: t2
        template: tti_Sketching_Art_1950s
        arguments:
          parameters:
          - name: prompt
            value: '{{inputs.parameters.prompt}}'
        dependencies: []

      - name: t3
        template: tti_Sketching_Art_2020s
        arguments:
          parameters:
          - name: prompt
            value: '{{inputs.parameters.prompt}}'
        dependencies: []

      - name: t4
        template: convert_to_png_early_1900s
        dependencies: [t1, t2, t3]

      - name: t5
        template: convert_to_png_1950s
        dependencies: [t1, t2, t3]

      - name: t6
        template: convert_to_png_2020s
        dependencies: [t1, t2, t3]
      - name: t7
        template: email_png_2020s
        dependencies: [t4, t5, t6]

  - name: tti_Sketching_Art_early_1900s
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: /generate_sketching_image/
      successCondition: response.statusCode == 200

  - name: tti_Sketching_Art_1950s
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: /generate_sketching_image/
      successCondition: response.statusCode == 200

  - name: tti_Sketching_Art_2020s
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: /generate_sketching_image/
      successCondition: response.statusCode == 200

  - name: convert_to_png_early_1900s
    http:
      method: POST
      url: /convert_to_png/
      successCondition: response.statusCode == 200

  - name: convert_to_png_1950s
    http:
      method: POST
      url: /convert_to_png/
      successCondition: response.statusCode == 200

  - name: convert_to_png_2020s
    http:
      method: POST
      url: /convert_to_png/
      successCondition: response.statusCode == 200

  - name: email_png_2020s
    http:
      method: POST
      url: /send_email/
      successCondition: response.statusCode == 200
