apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti-ukiyoe-art
        arguments:
          parameters:
          - name: prompt
            value: 'Japanese Ukiyo e-style picture: The Edo period with intricate
              details, vibrant colors, and characteristic themes.'

      - name: t2
        template: tti-charcoal-art
        arguments:
          parameters:
          - name: prompt
            value: 'Charcoal-style picture: The Renaissance period.'

      - name: t3
        template: tti-pastel-art
        arguments:
          parameters:
          - name: prompt
            value: 'Pastel-style picture: The Baroque period.'

      - name: t4
        template: tti-painting-art
        arguments:
          parameters:
          - name: prompt
            value: 'Lvngvncnt-style picture: The Victorian era.'

      - name: t5
        template: tti-charcoal-art-enhanced
        arguments:
          parameters:
          - name: prompt
            value: '{{tasks.t2.outputs.result}}'
        dependencies: [t2]

      - name: t6
        template: tti-pastel-art-enhanced
        arguments:
          parameters:
          - name: prompt
            value: '{{tasks.t3.outputs.result}}'
        dependencies: [t3]

      - name: t7
        template: tti-painting-art-enhanced
        arguments:
          parameters:
          - name: prompt
            value: '{{tasks.t4.outputs.result}}'
        dependencies: [t4]

      - name: t8
        template: tti-ukiyoe-art-enhanced
        arguments:
          parameters:
          - name: prompt
            value: '{{tasks.t1.outputs.result}}'
        dependencies: [t1]

  - name: tti-ukiyoe-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://example.com/generate_ukiyoe_image
      successCondition: response.statusCode == 200

  - name: tti-charcoal-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://example.com/generate_charcoal_image
      successCondition: response.statusCode == 200

  - name: tti-pastel-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://example.com/generate_pastel_image
      successCondition: response.statusCode == 200

  - name: tti-painting-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://example.com/generate_painting_image
      successCondition: response.statusCode == 200

  - name: tti-charcoal-art-enhanced
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://example.com/generate_charcoal_image
      successCondition: response.statusCode == 200

  - name: tti-pastel-art-enhanced
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://example.com/generate_pastel_image
      successCondition: response.statusCode == 200

  - name: tti-painting-art-enhanced
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://example.com/generate_painting_image
      successCondition: response.statusCode == 200

  - name: tti-ukiyoe-art-enhanced
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://example.com/generate_ukiyoe_image
      successCondition: response.statusCode == 200
