apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: Sketching art of the Jomon period (14,000–300 BCE)
      - name: t2
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: Sketching art of the Nara period (710–794)
      - name: t3
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: Sketching art of the Heian period (794–1185)
      - name: t4
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: Sketching art of the Kamakura period (1185–1333)
      - name: t5
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: Sketching art of the Muromachi period (1336–1573)
      - name: t6
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: Sketching art of the Azuchi-Momoyama period (1573–1603)
      - name: t7
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: Sketching art of the Edo period (1603–1868)
      - name: t8
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: Sketching art of the Meiji period (1868–1912)
      - name: t9
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: Sketching art of the Showa period (1926–1989)

  - name: tti-sketching-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://example.com/generate_sketching_image/
      headers:
        Content-Type: application/json
      body: |
        {
          "prompt": "{{inputs.parameters.prompt}}"
        }
      successCondition: response.statusCode == 200
