apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: width
      value: '1920'
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: width
    dag:
      tasks:
      - name: t1
        template: tti-Mosaic-Art
        arguments:
          parameters:
          - name: prompt
            value: Generate an image of a black cat in mosaic art style.
      - name: t2
        template: tti-Pastel-Art
        arguments:
          parameters:
          - name: prompt
            value: Generate an image of a black cat in pastel art style.
      - name: t3
        template: tti-Graffiti-Art
        arguments:
          parameters:
          - name: prompt
            value: Generate an image of a black cat in graffiti art style.
      - name: t4
        template: Image-Enhancement
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t1.outputs.result}}'
        dependencies: [t1]
      - name: t5
        template: tti-Mosaic-Art-Resize
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t4.outputs.result}}'
        dependencies: [t4]
      - name: t6
        template: tti-Mosaic-Art-Convert
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t5.outputs.result}}'
        dependencies: [t5]
      - name: t7
        template: Email-Image
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t6.outputs.result}}'
        dependencies: [t6]

  - name: tti-Mosaic-Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://example.com/generate_mosaic_image/
      body: '{"prompt": "{{inputs.parameters.prompt}}"}'
      successCondition: response.statusCode == 200

  - name: tti-Pastel-Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://example.com/generate_pastel_image/
      body: '{"prompt": "{{inputs.parameters.prompt}}"}'
      successCondition: response.statusCode == 200

  - name: tti-Graffiti-Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://example.com/generate_graffiti_image/
      body: '{"prompt": "{{inputs.parameters.prompt}}"}'
      successCondition: response.statusCode == 200

  - name: Image-Enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://example.com/image_enhance/
      body: '{"file": "{{inputs.parameters.file}}"}'
      successCondition: response.statusCode == 200

  - name: tti-Mosaic-Art-Resize
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://example.com/resize_image/
      body: '{"file": "{{inputs.parameters.file}}"}'
      successCondition: response.statusCode == 200

  - name: tti-Mosaic-Art-Convert
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://example.com/convert_to_png/
      body: '{"file": "{{inputs.parameters.file}}"}'
      successCondition: response.statusCode == 200

  - name: Email-Image
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://example.com/email_image/
      body: '{"file": "{{inputs.parameters.file}}"}'
      successCondition: response.statusCode == 200
