apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: width
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: width
    dag:
      tasks:
      - name: t1
        template: tti-Sketching-Art
        arguments:
          parameters:
          - name: prompt
            value: A bustling marketplace
        dependencies: []
      - name: t2
        template: image-to-pdf-conversion
        arguments:
          parameters:
          - name: file
            value: '{{ tasks.t1.outputs.artifact.imageUrl }}'
        dependencies:
        - t1
  - name: tti-Sketching-Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your.api.endpoint/tti_Sketching_Art
      successCondition: response.statusCode == 200
      headers:
        Content-Type: application/json
      body:
        prompt: '{{ inputs.parameters.prompt }}'
  - name: image-to-pdf-conversion
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://your.api.endpoint/image_to_pdf_conversion
      successCondition: response.statusCode == 200
      headers:
        Content-Type: multipart/form-data
      body:
        file: '{{ inputs.parameters.file }}'
