apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: width
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: width
    dag:
      tasks:
      - name: t1
        template: tti-Mosaic-Art
        arguments:
          parameters:
          - name: prompt
            value: '{{ inputs.parameters.width }}'
        dependencies: []
  - name: tti-Mosaic-Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your-api-url/generate_mosaic_image/  # Replace 'your-api-url' with the actual URL
      headers: {}
      json:
        prompt: '{{ inputs.parameters.prompt }}'
      successCondition: response.statusCode == 200
