apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti-Graffiti-Art
        arguments:
          parameters:
          - name: prompt
            value: '{{ workflow.parameters.prompt }}'
  - name: tti-Graffiti-Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: None    # URL for the 'tti_Graffiti_Art' API should be provided here
      successCondition: response.statusCode == 200
