apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: width
      value: 800
    - name: height
      value: 600
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: width
      - name: height
    dag:
      tasks:
      - name: t1
        template: tti-Graffiti-Art
        arguments:
          parameters:
          - name: prompt
            value: Urban jungle
      - name: t2
        template: image-resizing
        arguments:
          parameters:
          - name: width
            value: '{{inputs.parameters.width}}'
          - name: height
            value: '{{inputs.parameters.height}}'
          - name: file
            value: '{{tasks.t1.outputs.result}}'
        dependencies: [t1]

  - name: tti-Graffiti-Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: /generate_grafiti_image/
      successCondition: response.statusCode == 200
      json:
        prompt: '{{inputs.parameters.prompt}}'

  - name: image-resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: /resize_image/
      successCondition: response.statusCode == 200
      json:
        width: '{{inputs.parameters.width}}'
        height: '{{inputs.parameters.height}}'
        file: '{{inputs.parameters.file}}'
