apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti_Mosaic_Art
        arguments:
          parameters:
          - name: prompt
            value: black cat
      - name: t2
        dependencies: [t1]
        template: tti_Pastel_Art
        arguments:
          parameters:
          - name: prompt
            value: black cat
      - name: t3
        dependencies: [t2]
        template: tti_Graffiti_Art
        arguments:
          parameters:
          - name: prompt
            value: black cat
      - name: t4
        dependencies: [t3]
        template: Image_Enhancement
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t1.outputs.art-image}}'
      - name: t5
        dependencies: [t4]
        template: Resize_Image
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t4.outputs.art-image}}'
      - name: t6
        dependencies: [t5]
        template: Convert_to_PNG
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t5.outputs.art-image}}'
      - name: t7
        dependencies: [t6]
        template: Email_Image
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t6.outputs.art-image}}'

  - name: tti_Mosaic_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: https://yourapiendpoint.com/generate_mosaic_image/
      headers:
        Content-Type: application/json
      body: |
        {
          "prompt": "{{inputs.parameters.prompt}}"
        }
      successCondition: response.statusCode == 200

  - name: tti_Pastel_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: https://yourapiendpoint.com/generate_pastel_image/
      headers:
        Content-Type: application/json
      body: |
        {
          "prompt": "{{inputs.parameters.prompt}}"
        }
      successCondition: response.statusCode == 200

  - name: tti_Graffiti_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: https://yourapiendpoint.com/generate_grafiti_image/
      headers:
        Content-Type: application/json
      body: |
        {
          "prompt": "{{inputs.parameters.prompt}}"
        }
      successCondition: response.statusCode == 200

  - name: Image_Enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: https://yourapiendpoint.com/image_enhance/
      headers:
        Content-Type: multipart/form-data
      body: |
        {
          "file": "{{inputs.parameters.file}}"
        }
      successCondition: response.statusCode == 200

  - name: Resize_Image
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: https://yourapiendpoint.com/resize_image/
      headers:
        Content-Type: multipart/form-data
      body: |
        {
          "file": "{{inputs.parameters.file}}",
          "dimensions": "1920x1080"
        }
      successCondition: response.statusCode == 200

  - name: Convert_to_PNG
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: https://yourapiendpoint.com/convert_to_png/
      headers:
        Content-Type: multipart/form-data
      body: |
        {
          "file": "{{inputs.parameters.file}}"
        }
      successCondition: response.statusCode == 200

  - name: Email_Image
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: https://yourapiendpoint.com/email_image/
      headers:
        Content-Type: multipart/form-data
      body: |
        {
          "file": "{{inputs.parameters.file}}",
          "email": "recipient@example.com"
        }
      successCondition: response.statusCode == 200
