apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti-futuristic-art
        arguments:
          parameters:
          - name: prompt
            value: Generate a futuristic image of an iPhone.

      - name: t2
        dependencies: [t1]
        template: image-enhancement
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t1.outputs.result}}'

      - name: t3
        dependencies: [t2]
        template: image-resizing
        arguments:
          parameters:
          - name: width
            value: '500'
          - name: height
            value: '500'
          - name: file
            value: '{{tasks.t2.outputs.result}}'

      - name: t4
        dependencies: [t3]
        template: image-enhancement
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t3.outputs.result}}'

      - name: t5
        dependencies: [t4]
        template: image-to-pdf-conversion
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t4.outputs.result}}'

      - name: t6
        dependencies: [t5]
        template: send-to-john
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t5.outputs.result}}'

      - name: t7
        dependencies: [t6]
        template: send-to-kody
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t5.outputs.result}}'

      - name: t8
        dependencies: [t7]
        template: send-to-mike
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t5.outputs.result}}'

  - name: tti-futuristic-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://<your-futuristic-art-service-url>
      successCondition: response.statusCode == 200

  - name: image-enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://<your-image-enhancement-service-url>
      successCondition: response.statusCode == 200

  - name: image-resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://<your-image-resizing-service-url>
      successCondition: response.statusCode == 200

  - name: image-to-pdf-conversion
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://<your-image-to-pdf-service-url>
      successCondition: response.statusCode == 200

  - name: send-to-john
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://<your-send-to-john-service-url>
      successCondition: response.statusCode == 200

  - name: send-to-kody
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://<your-send-to-kody-service-url>
      successCondition: response.statusCode == 200

  - name: send-to-mike
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://<your-send-to-mike-service-url>
      successCondition: response.statusCode == 200
