apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-workflow-
spec:
  arguments:
    parameters:
    - name: width
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: width
    dag:
      tasks:
      - name: t1
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of a Labrador Retriever.
        dependencies: []
      - name: t2
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of a German Shepherd.
        dependencies: [t1]
      - name: t3
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of a Golden Retriever.
        dependencies: [t2]
      - name: t4
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of a Bulldog.
        dependencies: [t3]
      - name: t5
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of a Poodle.
        dependencies: [t4]
      - name: t6
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of a Beagle.
        dependencies: [t5]
      - name: t7
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of a Rottweiler.
        dependencies: [t6]
      - name: t8
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of a Dachshund.
        dependencies: [t7]
      - name: t9
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of a Siberian Husky.
        dependencies: [t8]
      - name: t10
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of a Shih Tzu.
        dependencies: [t9]
  - name: tti_Sketching_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your-api-endpoint.com/generate_sketching_image/
      body:
        prompt: '{{inputs.parameters.prompt}}'
      successCondition: response.statusCode == 200
