apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t0
        template: tti-Animation-Art
        arguments:
          parameters:
          - name: prompt
            value: Generate an animated image of a high school boy in Japan.
      - name: t1
        template: tti-Animation-Art
        arguments:
          parameters:
          - name: prompt
            value: Generate an animated image of a high school girl in Japan.
      - name: t2
        template: tti-Animation-Art
        arguments:
          parameters:
          - name: prompt
            value: Enhance the animated image of the high school boy.
      - name: t3
        template: tti-Futuristic-Art
        arguments:
          parameters:
          - name: prompt
            value: Enhance the animated image of the high school girl.
      - name: t4
        template: Image-Resizing
        arguments:
          parameters:
          - name: width
            value: 500
          - name: height
            value: 800
          - name: file
            value: '{{tasks.t3.outputs.result}}'
        dependencies: [t3]
      - name: t5
        template: Image-Resizing
        arguments:
          parameters:
          - name: width
            value: 500
          - name: height
            value: 800
          - name: file
            value: '{{tasks.t3.outputs.result}}'
        dependencies: [t3]
      - name: t6
        template: Image-Format-Converter
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t3.outputs.result}}'
          - name: output_format
            value: PNG
        dependencies: [t3]
      - name: t7
        template: Image-Format-Converter
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t3.outputs.result}}'
          - name: output_format
            value: JPEG
        dependencies: [t3]
  - name: tti-Animation-Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://tti_animation_art_endpoint
      headers:
        Content-Type: application/json
      body: |
        {
          "prompt": "{{inputs.parameters.prompt}}"
        }
      successCondition: response.statusCode == 200
  - name: tti-Futuristic-Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://tti_futuristic_art_endpoint
      headers:
        Content-Type: application/json
      body: |
        {
          "prompt": "{{inputs.parameters.prompt}}"
        }
      successCondition: response.statusCode == 200
  - name: Image-Resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://image_resizing_endpoint
      headers:
        Content-Type: application/json
      body: |
        {
          "width": "{{inputs.parameters.width}}",
          "height": "{{inputs.parameters.height}}",
          "file": "{{inputs.parameters.file}}"
        }
      successCondition: response.statusCode == 200
  - name: Image-Format-Converter
    inputs:
      parameters:
      - name: file
      - name: output_format
    http:
      method: POST
      url: http://image_format_converter_endpoint
      headers:
        Content-Type: application/json
      body: |
        {
          "file": "{{inputs.parameters.file}}",
          "output_format": "{{inputs.parameters.output_format}}"
        }
      successCondition: response.statusCode == 200
