apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Create a sketch of a castle surrounded by a dense forest.

      - name: t2
        template: Image_Resizing
        arguments:
          parameters:
          - name: width
            value: 1280
          - name: height
            value: 720
          - name: file
            value: '{{tasks.t1.outputs.artifacts.sketch_image}}'
        dependencies: [t1]

      - name: t3
        template: Image_Enhancement
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t2.outputs.artifacts.resized_image}}'
        dependencies: [t2]

      - name: t4
        template: image_to_pdf_conversion
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t3.outputs.artifacts.enhanced_image}}'
        dependencies: [t3]

      - name: t5
        template: send_email_with_attachment
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t4.outputs.artifacts.pdf_file}}'
        dependencies: [t4]

  - name: tti_Sketching_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your-api-server/tti_Sketching_Art
      headers: {}
      body: '{ "prompt": "{{inputs.parameters.prompt}}" }'
      successCondition: response.statusCode == 200
    outputs:
      artifacts:
      - name: sketch_image
        path: /tmp/sketch_image.png
        archive:
          none: {}

  - name: Image_Resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://your-api-server/resize_image
      headers: {}
      body: '{ "width": "{{inputs.parameters.width}}", "height": "{{inputs.parameters.height}}",
        "file": "{{inputs.parameters.file}}" }'
      successCondition: response.statusCode == 200
    outputs:
      artifacts:
      - name: resized_image
        path: /tmp/resized_image.png
        archive:
          none: {}

  - name: Image_Enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://your-api-server/image_enhance
      headers: {}
      body: '{ "file": "{{inputs.parameters.file}}" }'
      successCondition: response.statusCode == 200
    outputs:
      artifacts:
      - name: enhanced_image
        path: /tmp/enhanced_image.jpg
        archive:
          none: {}

  - name: image_to_pdf_conversion
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://your-api-server/convert_to_pdf
      headers: {}
      body: '{ "file": "{{inputs.parameters.file}}" }'
      successCondition: response.statusCode == 200
    outputs:
      artifacts:
      - name: pdf_file
        path: /tmp/output.pdf
        archive:
          none: {}

  - name: send_email_with_attachment
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://your-email-server/send
      headers: {}
      body: '{ "file": "{{inputs.parameters.file}}", "email": "colleague@example.com"
        }'
      successCondition: response.statusCode == 200
