apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti-pastel-art
        arguments:
          parameters:
          - name: prompt
            value: Create a pastel art image of a serene beach at sunset with palm
              trees.
      - name: t2
        template: convert-to-jpeg
        dependencies: [t1]
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t1.outputs.parameters.image_file}}'
      - name: t3
        template: resize-image
        dependencies: [t2]
        arguments:
          parameters:
          - name: width
            value: 1024
          - name: height
            value: 768
          - name: file
            value: '{{tasks.t2.outputs.parameters.image_file}}'
      - name: t4
        template: enhance-image
        dependencies: [t3]
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t3.outputs.parameters.image_file}}'
      - name: t5
        template: email-image
        dependencies: [t4]
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t4.outputs.parameters.image_file}}'

  - name: tti-pastel-art
    inputs:
      parameters:
      - name: prompt
    outputs:
      parameters:
      - name: image_file
        valueFrom:
          jsonPath: '{.result.image_file}'
    http:
      method: POST
      url: http://example.com/generate_pastel_image/
      headers:
        Content-Type: application/json
      json:
        prompt: '{{inputs.parameters.prompt}}'
      successCondition: response.statusCode == 200

  - name: convert-to-jpeg
    inputs:
      parameters:
      - name: file
    outputs:
      parameters:
      - name: image_file
        valueFrom:
          jsonPath: '{.result.image_file}'
    http:
      method: POST
      url: http://example.com/convert_to_jpeg/
      headers:
        Content-Type: application/json
      json:
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200

  - name: resize-image
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    outputs:
      parameters:
      - name: image_file
        valueFrom:
          jsonPath: '{.result.image_file}'
    http:
      method: POST
      url: http://example.com/resize_image/
      headers:
        Content-Type: application/json
      json:
        width: '{{inputs.parameters.width}}'
        height: '{{inputs.parameters.height}}'
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200

  - name: enhance-image
    inputs:
      parameters:
      - name: file
    outputs:
      parameters:
      - name: image_file
        valueFrom:
          jsonPath: '{.result.image_file}'
    http:
      method: POST
      url: http://example.com/image_enhance/
      headers:
        Content-Type: application/json
      json:
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200

  - name: email-image
    inputs:
      parameters:
      - name: file
    outputs:
      parameters:
      - name: result
        valueFrom:
          jsonPath: '{.result}'
    http:
      method: POST
      url: http://example.com/send_email/
      headers:
        Content-Type: application/json
      json:
        file: '{{inputs.parameters.file}}'
        email: friend@example.com
      successCondition: response.statusCode == 200
