apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: prompt
      value: Create a digital art piece of a futuristic cityscape at night, with neon
        lights and flying cars.
    - name: width
      value: 1920
    - name: height
      value: 1080
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: prompt
      - name: width
      - name: height
    dag:
      tasks:
      - name: t1
        template: tti_Futuristic_Art
        arguments:
          parameters:
          - name: prompt
            value: '{{inputs.parameters.prompt}}'
      - name: t2
        template: Image_Resizing
        arguments:
          parameters:
          - name: width
            value: '{{inputs.parameters.width}}'
          - name: height
            value: '{{inputs.parameters.height}}'
          - name: file
            value: '{{tasks.t1.outputs.result}}'
        dependencies: [t1]
      - name: t3
        template: Image_Enhancement
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t2.outputs.result}}'
        dependencies: [t2]
      - name: t4
        template: image_to_pdf_conversion
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t3.outputs.result}}'
        dependencies: [t3]
      - name: t5
        template: Send_Email
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t4.outputs.result}}'
        dependencies: [t4]
  - name: tti_Futuristic_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your-futuristic-art-api-url
      successCondition: response.statusCode == 200

  - name: Image_Resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://your-image-resizing-api-url
      successCondition: response.statusCode == 200

  - name: Image_Enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://your-image-enhancement-api-url
      successCondition: response.statusCode == 200

  - name: image_to_pdf_conversion
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://your-image-to-pdf-conversion-api-url
      successCondition: response.statusCode == 200

  - name: Send_Email
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://your-send-email-api-url
      successCondition: response.statusCode == 200
