apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti_Charcoal_Art
        arguments:
          parameters:
          - name: prompt
            value: Create a charcoal art image of a New York landscape in 1990.
        dependencies: []
      - name: t2
        template: tti_Charcoal_Art
        arguments:
          parameters:
          - name: prompt
            value: '{{tasks.t1.outputs.parameters.result}}'
        dependencies:
        - t1
      - name: t3
        template: Image_Resizing
        arguments:
          parameters:
          - name: width
            value: 800
          - name: height
            value: 600
          - name: file
            value: '{{tasks.t2.outputs.parameters.result}}'
        dependencies:
        - t2
      - name: t4
        template: Image_Enhancement
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t3.outputs.parameters.result}}'
        dependencies:
        - t3
      - name: t5
        template: Send_Email
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t4.outputs.parameters.result}}'
        dependencies:
        - t4

  - name: tti_Charcoal_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your-api-endpoint/generate_charcoal_image/
      successCondition: response.statusCode == 200
      body: |
        {
          "prompt": "{{inputs.parameters.prompt}}"
        }

  - name: Image_Resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://your-api-endpoint/resize_image/
      successCondition: response.statusCode == 200
      body: |
        {
          "width": "{{inputs.parameters.width}}",
          "height": "{{inputs.parameters.height}}",
          "file": "{{inputs.parameters.file}}"
        }

  - name: Image_Enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://your-api-endpoint/image_enhance/
      successCondition: response.statusCode == 200
      body: |
        {
          "file": "{{inputs.parameters.file}}"
        }

  - name: Send_Email
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://your-api-endpoint/send_email/
      successCondition: response.statusCode == 200
      body: |-
        {
          "file": "{{inputs.parameters.file}}"
        }
