apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: futuristic-art-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: generate-futuristic-art
        arguments:
          parameters:
          - name: prompt
            value: '{{tasks.t1.result}}'
        dependencies: []

  - name: generate-futuristic-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your-api-endpoint-url/generate_futuristic_image/
      successCondition: response.statusCode == 200
