apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: Your user prompt here

  - name: tti-sketching-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your-api-server/generate_sketching_image/
      successCondition: response.statusCode == 200
      headers:
        Content-Type: application/json
      body: |-
        {
          "prompt": "{{inputs.parameters.prompt}}"
        }
