apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: prompt
    - name: file
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: prompt
      - name: file
    dag:
      tasks:
      - name: t1
        template: tti-futuristic-art
        arguments:
          parameters:
          - name: prompt
            value: '{{ inputs.parameters.prompt }}'
        dependencies: []
      - name: t2
        template: image-to-pdf-conversion
        arguments:
          parameters:
          - name: file
            value: '{{ inputs.parameters.file }}'
        dependencies:
        - t1
  - name: tti-futuristic-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url:
      successCondition: response.statusCode == 200
  - name: image-to-pdf-conversion
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url:
      successCondition: response.statusCode == 200
