apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Create a sketch of a castle surrounded by a dense forest.
        dependencies: []

      - name: t2
        template: Image_Resizing
        arguments:
          parameters:
          - name: width
            value: '1280'
          - name: height
            value: '720'
          - name: file
            value: '{{tasks.t2.outputs.result}}'
        dependencies: [t2]

      - name: t3
        template: Image_Enhancement
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t2.outputs.result}}'
        dependencies: [t2]
      - name: t4
        template: image_to_pdf_conversion
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t2.outputs.result}}'
        dependencies: [t2]
      - name: t5
        template: email_PDF
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t4.outputs.result}}'
        dependencies: [t4]

  - name: tti_Sketching_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: <Insert_Real_URL_Here>
      successCondition: response.statusCode == 200

  - name: Image_Resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: <Insert_Real_URL_Here>
      successCondition: response.statusCode == 200

  - name: Image_Enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: <Insert_Real_URL_Here>
      successCondition: response.statusCode == 200

  - name: image_to_pdf_conversion
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: <Insert_Real_URL_Here>
      successCondition: response.statusCode == 200

  - name: email_PDF
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: <Insert_Real_URL_Here>  # An endpoint that handles sending email with attachments
      successCondition: response.statusCode == 200
