apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti-charcoal-art
        arguments:
          parameters:
          - name: prompt
            value: Charcoal-style picture of a serene forest
      - name: t2
        template: image-resizing
        arguments:
          parameters:
          - name: width
            value: 1920
          - name: height
            value: 1080
          - name: file
            value: '{{tasks.t1.outputs.result}}'
        dependencies:
        - t1
      - name: t3
        template: image-to-pdf
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t2.outputs.result}}'
        dependencies:
        - t2

  - name: tti-charcoal-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://example.com/tti-charcoal-art
      body:
        prompt: '{{inputs.parameters.prompt}}'
      successCondition: response.statusCode == 200

  - name: image-resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://example.com/resize_image
      body:
        width: '{{inputs.parameters.width}}'
        height: '{{inputs.parameters.height}}'
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200

  - name: image-to-pdf
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://example.com/convert_to_pdf
      body:
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200
