apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: Create a sketching art image of a bustling marketplace.
        dependencies: []

      - name: t2
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: Convert the sketching art image of the bustling marketplace to
              a PNG format.
        dependencies: [t1]

      - name: t3
        template: image-resizing
        arguments:
          parameters:
          - name: width
            value: 800
          - name: height
            value: 600
          - name: file
            value: '{{ tasks.t2.outputs.artifacts.sketching_image }}'
        dependencies: [t2]

  - name: tti-sketching-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://sketching-art-endpoint.com/generate_sketching_image/
      successCondition: response.statusCode == 200
      body: |
        {
          "prompt": "{{ inputs.parameters.prompt }}"
        }

  - name: image-resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://image-resizing-endpoint.com/resize_image/
      successCondition: response.statusCode == 200
      body: |
        {
          "width": {{ inputs.parameters.width }},
          "height": {{ inputs.parameters.height }},
          "file": "{{ inputs.parameters.file }}"
        }
      outputs:
        artifacts:
        - name: resized_image
          path: /outputs/resized_image.png
