apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti_Charcoal_Art
        arguments:
          parameters:
          - name: prompt
            value: Create a charcoal art image of a New York landscape in 1990.
      - name: t2
        dependencies: [t1]
        template: tti_Charcoal_Art
        arguments:
          parameters:
          - name: prompt
            value: Convert the charcoal art image of the New York landscape in 1990
              to PNG format.
      - name: t3
        dependencies: [t2]
        template: Image_Resizing
        arguments:
          parameters:
          - name: width
            value: 800
          - name: height
            value: 600
          - name: file
            value: '{{tasks.t2.outputs.result}}'
      - name: t4
        dependencies: [t3]
        template: Image_Enhancement
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t3.outputs.result}}'
      - name: t5
        dependencies: [t4]
        template: Send_Email
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t4.outputs.result}}'

  - name: tti_Charcoal_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://example_domain/generate_charcoal_image/
      headers:
        Content-Type: application/json
      body: '{"prompt": "{{inputs.parameters.prompt}}"}'
      successCondition: response.statusCode == 200

  - name: Image_Resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://example_domain/resize_image/
      headers:
        Content-Type: multipart/form-data
      formData:
        width: '{{inputs.parameters.width}}'
        height: '{{inputs.parameters.height}}'
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200

  - name: Image_Enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://example_domain/image_enhance/
      headers:
        Content-Type: multipart/form-data
      formData:
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200

  - name: Send_Email
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://example_domain/send_email/
      headers:
        Content-Type: multipart/form-data
      formData:
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200
