apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti-futuristic-art
        arguments:
          parameters:
          - name: prompt
            value: Create a digital art piece of a futuristic cityscape at night,
              with neon lights and flying cars.
      - name: t2
        template: image-resizing
        arguments:
          parameters:
          - name: width
            value: '1920'
          - name: height
            value: '1080'
          - name: file
            value: '{{tasks.t1.outputs.result}}'
        dependencies: [t1]
      - name: t3
        template: image-enhancement
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t2.outputs.result}}'
        dependencies: [t2]
      - name: t4
        template: image-to-pdf-conversion
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t3.outputs.result}}'
        dependencies: [t3]
      - name: t5
        template: send-email
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t4.outputs.result}}'
        dependencies: [t4]

  - name: tti-futuristic-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: <your-tti-futuristic-art-api-endpoint>
      headers:
        Content-Type: application/json
      body:
        prompt: '{{inputs.parameters.prompt}}'
      successCondition: response.statusCode == 200

  - name: image-resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: <your-image-resizing-api-endpoint>
      headers:
        Content-Type: application/json
      body:
        width: '{{inputs.parameters.width}}'
        height: '{{inputs.parameters.height}}'
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200

  - name: image-enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: <your-image-enhancement-api-endpoint>
      headers:
        Content-Type: application/json
      body:
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200

  - name: image-to-pdf-conversion
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: <your-image-to-pdf-conversion-api-endpoint>
      headers:
        Content-Type: application/json
      body:
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200

  - name: send-email
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: <your-send-email-api-endpoint>
      headers:
        Content-Type: application/json
      body:
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200
