apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti-pastel-art
        arguments:
          parameters:
          - name: prompt
            value: Create a pastel art image of a sunset over the ocean.
      - name: t2
        dependencies: [t1]
        template: tti-pastel-art
        arguments:
          parameters:
          - name: prompt
            value: Convert the pastel art image of the sunset over the ocean to a
              JPEG format.

      - name: t3
        dependencies: [t2]
        template: image-resizing
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t2.outputs.result}}'
          - name: width
            value: 1024
          - name: height
            value: 768

      - name: t4
        dependencies: [t3]
        template: image-enhancement
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t3.outputs.result}}'

      - name: t5
        dependencies: [t4]
        template: send-email
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t4.outputs.result}}'

  - name: tti-pastel-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://myapi.com/tti_pastel_art
      json:
        prompt: '{{inputs.parameters.prompt}}'
      successCondition: response.statusCode == 200

  - name: image-resizing
    inputs:
      parameters:
      - name: file
      - name: width
      - name: height
    http:
      method: POST
      url: http://myapi.com/resize_image/
      json:
        width: '{{inputs.parameters.width}}'
        height: '{{inputs.parameters.height}}'
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200

  - name: image-enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://myapi.com/image_enhance/
      json:
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200

  - name: send-email
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://myemailapi.com/send_email/
      json:
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200
