apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: width
    - name: height
    - name: file
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    dag:
      tasks:
      - name: t1
        dependencies: []
        template: tti_Futuristic_Art
        arguments:
          parameters:
          - name: prompt
            value: Create a digital art piece of a futuristic cityscape.

      - name: t2
        dependencies: [t1]
        template: tti_Pastel_Art
        arguments:
          parameters:
          - name: prompt
            value: '{{{{tasks.t1.outputs.result}}}}'
      - name: t3
        dependencies: [t2]
        template: Image_Resizing
        arguments:
          parameters:
          - name: width
            value: '{{{{inputs.parameters.width}}}}'
          - name: height
            value: '{{{{inputs.parameters.height}}}}'
          - name: file
            value: '{{{{tasks.t2.outputs.result}}}}'
  - name: tti_Futuristic_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your.api.endpoint/generate_futuristic_image/
      successCondition: response.statusCode == 200

  - name: tti_Pastel_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your.api.endpoint/generate_pastel_image/
      successCondition: response.statusCode == 200

  - name: Image_Resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://your.api.endpoint/resize_image/
      headers:
        Content-Type: multipart/form-data
      successCondition: response.statusCode == 200
