apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti-pastel-art
        arguments:
          parameters:
          - name: prompt
            value: A peaceful beach at sunrise
      - name: t2
        template: image-enhancement
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t1.outputs.parameters.image}}'
        dependencies: [t1]

  - name: tti-pastel-art
    inputs:
      parameters:
      - name: prompt
    outputs:
      parameters:
      - name: image
        valueFrom:
          path: /tmp/generated_img.png
    script:
      image: python:3.8
      command: [python]
      source: |
        from fastapi import FastAPI
        from fastapi.responses import FileResponse
        from PIL import Image
        from diffusers import StableDiffusionPipeline, DPMSolverMultistepScheduler
        import torch
        import sys

        app = FastAPI()

        def load_model():
            model_id = 'JamesFlare/pastel-mix'
            pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
            pipe.scheduler = DPMSolverMultistepScheduler.from_config(pipe.scheduler.config)
            pipe = pipe.to('cuda')
            return pipe

        def process_data(prompt, pipe):
            response = pipe(prompt).images[0]
            return response

        @app.post("/generate_pastel_image/")
        async def generate_image(prompt:str):
            try:
                pipe = load_model()
                prompt = "Pastel-style picture: " + prompt
                response = process_data(prompt, pipe)
                response.save('/tmp/generated_img.png')
                return FileResponse('/tmp/generated_img.png')
            except Exception as e:
                raise HTTPException(status_code=500, detail=str(e))

        if __name__ == "__main__":
            prompt = sys.argv[1]
            app.run(host="0.0.0.0", port=8000)

  - name: image-enhancement
    inputs:
      parameters:
      - name: file
    outputs:
      parameters:
      - name: enhanced_image
        valueFrom:
          path: /tmp/final_image.jpg
    script:
      image: python:3.8
      command: [python]
      source: |-
        from fastapi import FastAPI, HTTPException, UploadFile
        from fastapi.responses import FileResponse
        from pathlib import Path
        import cv2
        import numpy as np
        from PIL import Image
        import sys

        app = FastAPI()

        @app.post('/image_enhance/')
        async def enhance_image(file: UploadFile):
            try:
                image_name = '/tmp/' + file.filename
                image = Image.open(file.file)
                image.save(image_name)
                img = cv2.imread(image_name)
                denoised_image = cv2.fastNlMeansDenoisingColored(img, None, 10, 10, 7, 21)
                contrast_stretched_image = cv2.normalize(denoised_image, None, 255, 0, cv2.NORM_MINMAX, cv2.CV_8UC1)
                kernel = np.array([[0, -1, 0], [-1, 5, -1], [0, -1, 0]], np.float32)
                sharpened_image = cv2.filter2D(contrast_stretched_image, -1, kernel=kernel)
                brightness_image = cv2.convertScaleAbs(sharpened_image, alpha=1, beta=5)
                gamma = 1.5
                lookup_table = np.array([((i / 255.0) ** gamma) * 255 for i in np.arange(0, 256)]).astype("uint8")
                gamma_corrected_image = cv2.LUT(brightness_image, lookup_table)
                final_name = '/tmp/final_image.jpg'
                cv2.imwrite(final_name, gamma_corrected_image)
                return FileResponse(final_name, media_type='image/jpg', filename=final_name)
            except Exception as e:
                raise HTTPException(status_code=500, detail=str(e))

        if __name__ == "__main__":
            # Simulate file upload for the script
            filename = sys.argv[1]
            app.run(host="0.0.0.0", port=8000)
