apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: width
    - name: height
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: width
      - name: height
    dag:
      tasks:
      - name: t1
        template: tti_mosaic_art
        arguments:
          parameters:
          - name: prompt
            value: Ancient Roman architecture
      - name: t2
        template: image_resizing
        dependencies: [t1]
        arguments:
          parameters:
          - name: width
            value: '{{inputs.parameters.width}}'
          - name: height
            value: '{{inputs.parameters.height}}'
          - name: file
            value: '{{tasks.t1.outputs.result}}'
  - name: tti_mosaic_art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your-api-endpoint/generate_mosaic_image/
      successCondition: response.statusCode == 200
  - name: image_resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://your-api-endpoint/resize_image/
      successCondition: response.statusCode == 200
