apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: prompt
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: prompt
    dag:
      tasks:
      - name: t1
        template: tti-animation-art
        arguments:
          parameters:
          - name: prompt
            value: '{{tasks.t1.result}}'
        dependencies: []
      - name: t2
        template: tti-animation-art
        arguments:
          parameters:
          - name: prompt
            value: '{{tasks.t2.result}}'
        dependencies: []
  - name: tti-animation-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url:
      successCondition: response.statusCode == 200
