apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: width
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: width
    dag:
      tasks:
      - name: t1
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: A bustling marketplace
        dependencies: []

      - name: t2
        template: image_to_pdf_conversion
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t1.outputs.result}}'  # Assuming task t1 outputs the file path or binary content of the image.
        dependencies:
        - t1
  - name: tti_Sketching_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: # URL to call the tti_Sketching_Art service
      successCondition: response.statusCode == 200
  - name: image_to_pdf_conversion
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: # URL to call the image_to_pdf_conversion service
      successCondition: response.statusCode == 200
