apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti-mosaic-art
        arguments:
          parameters:
          - name: prompt
            value: Generate an image of a black cat in mosaic art style.
      - name: t2
        template: tti-pastel-art
        arguments:
          parameters:
          - name: prompt
            value: Generate an image of a black cat in pastel art style.
      - name: t3
        template: tti-graffiti-art
        arguments:
          parameters:
          - name: prompt
            value: Generate an image of a black cat in graffiti art style.
      - name: t4
        template: image-enhancement
        arguments:
          parameters:
          - name: file
            value: '{{ tasks.t1.outputs.artifact.images }}'
        dependencies: [t1]
      - name: t5
        template: resize-mosaic-art
        arguments:
          parameters:
          - name: file
            value: '{{ tasks.t4.outputs.artifact.enhanced_image }}'
        dependencies: [t4]
      - name: t6
        template: convert-to-png
        arguments:
          parameters:
          - name: file
            value: '{{ tasks.t5.outputs.artifact.resized_image }}'
        dependencies: [t5]
      - name: t7
        template: email-image
        arguments:
          parameters:
          - name: file
            value: '{{ tasks.t6.outputs.artifact.png_image }}'
        dependencies: [t6]

  - name: tti-mosaic-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://example.com/generate_mosaic_image/
      successCondition: response.statusCode == 200

  - name: tti-pastel-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://example.com/generate_pastel_image/
      successCondition: response.statusCode == 200

  - name: tti-graffiti-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://example.com/generate_graffiti_image/
      successCondition: response.statusCode == 200

  - name: image-enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://example.com/image_enhance/
      successCondition: response.statusCode == 200

  - name: resize-mosaic-art
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://example.com/resize_mosaic_image/
      successCondition: response.statusCode == 200

  - name: convert-to-png
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://example.com/convert_to_png/
      successCondition: response.statusCode == 200

  - name: email-image
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://example.com/email_image/
      successCondition: response.statusCode == 200
