apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti-painting-art
        arguments:
          parameters:
          - name: prompt
            value: '{{workflow.parameters.prompt}}'
      - name: t2
        template: tti-pastel-art
        dependencies: [t1]
        arguments:
          parameters:
          - name: prompt
            value: '{{workflow.parameters.prompt}}'
      - name: t3
        template: tti-sketching-art
        dependencies: [t2]
        arguments:
          parameters:
          - name: prompt
            value: '{{workflow.parameters.prompt}}'
      - name: t4
        template: image-resizing
        dependencies: [t3]
        arguments:
          parameters:
          - name: width
            value: '1920'
          - name: height
            value: '1080'
          - name: file
            value: '{{tasks.t3.outputs.result}}'
      - name: t5
        template: image-enhancement
        dependencies: [t4]
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t4.outputs.result}}'
      - name: t6
        template: tti-mosaic-art
        dependencies: [t5]
        arguments:
          parameters:
          - name: prompt
            value: '{{workflow.parameters.prompt}}'

  - name: tti-painting-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: <URL_FOR_TTI_PAINTING_ART_API>
      successCondition: response.statusCode == 200

  - name: tti-pastel-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: <URL_FOR_TTI_PASTEL_ART_API>
      successCondition: response.statusCode == 200

  - name: tti-sketching-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: <URL_FOR_TTI_SKETCHING_ART_API>
      successCondition: response.statusCode == 200

  - name: image-resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: <URL_FOR_IMAGE_RESIZING_API>
      successCondition: response.statusCode == 200

  - name: image-enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: <URL_FOR_IMAGE_ENHANCEMENT_API>
      successCondition: response.statusCode == 200

  - name: tti-mosaic-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: <URL_FOR_TTI_MOSAIC_ART_API>
      successCondition: response.statusCode == 200
