apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: width
      value: '1024'
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: width
    dag:
      tasks:
      - name: t1
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of the Showa period (1926–1989).
        dependencies: []
      - name: t2
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of the Jomon period (14,000–300
              BCE).
        dependencies: []
      - name: t3
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of the Nara period (710–794).
        dependencies: []
      - name: t4
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of the Heian period (794–1185).
        dependencies: []
      - name: t5
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of the Kamakura period (1185–1333).
        dependencies: []
      - name: t6
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of the Muromachi period (1336–1573).
        dependencies: []
      - name: t7
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of the Azuchi-Momoyama period
              (1573–1603).
        dependencies: []
      - name: t8
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of the Edo period (1603–1868).
        dependencies: []
      - name: t9
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of the Meiji period (1868–1912).
        dependencies: []
  - name: tti_Sketching_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://example.com/generate_sketching_image/
      body:
        parameter: prompt
      successCondition: response.statusCode == 200
