apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti_Charcoal_Art
        arguments:
          parameters:
          - name: prompt
            value: Depiction of the Renaissance period

      - name: t2
        template: tti_Pastel_Art
        arguments:
          parameters:
          - name: prompt
            value: Depiction of the Baroque period
        dependencies: [t1]

      - name: t3
        template: tti_Painting_Art
        arguments:
          parameters:
          - name: prompt
            value: Depiction of the Victorian era
        dependencies: [t1]

      - name: t4
        template: tti_Ukiyo-e_Art
        arguments:
          parameters:
          - name: prompt
            value: Depiction of the Edo period
        dependencies: [t1]

      - name: t5
        template: enhance_tti_Charcoal_Art
        arguments:
          parameters:
          - name: prompt
            value: '{{{{ tasks.t1.result }}}}'
        dependencies: [t1, t2, t3, t4]

      - name: t6
        template: enhance_tti_Pastel_Art
        arguments:
          parameters:
          - name: prompt
            value: '{{{{ tasks.t2.result }}}}'
        dependencies: [t1, t2, t3, t4]

      - name: t7
        template: enhance_tti_Painting_Art
        arguments:
          parameters:
          - name: prompt
            value: '{{{{ tasks.t3.result }}}}'
        dependencies: [t1, t2, t3, t4]

      - name: t8
        template: enhance_tti_Ukiyo-e_Art
        arguments:
          parameters:
          - name: prompt
            value: '{{{{ tasks.t4.result }}}}'
        dependencies: [t1, t2, t3, t4]

  - name: tti_Charcoal_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your-charcoal-art-endpoint
      successCondition: response.statusCode == 200

  - name: tti_Pastel_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your-pastel-art-endpoint
      successCondition: response.statusCode == 200

  - name: tti_Painting_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your-painting-art-endpoint
      successCondition: response.statusCode == 200

  - name: tti_Ukiyo-e_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your-ukiyoe-art-endpoint
      successCondition: response.statusCode == 200

  - name: enhance_tti_Charcoal_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your-enhance-charcoal-art-endpoint
      successCondition: response.statusCode == 200

  - name: enhance_tti_Pastel_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your-enhance-pastel-art-endpoint
      successCondition: response.statusCode == 200

  - name: enhance_tti_Painting_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your-enhance-painting-art-endpoint
      successCondition: response.statusCode == 200

  - name: enhance_tti_Ukiyo-e_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your-enhance-ukiyoe-art-endpoint
      successCondition: response.statusCode == 200
