apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: width
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: width
    dag:
      tasks:
      - name: t1
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of a Labrador Retriever.
        dependencies: []
      - name: t2
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of a German Shepherd.
        dependencies: []
      - name: t3
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of a Golden Retriever.
        dependencies: []
      - name: t4
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of a Bulldog.
        dependencies: []
      - name: t5
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of a Poodle.
        dependencies: []
      - name: t6
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of a Beagle.
        dependencies: []
      - name: t7
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of a Rottweiler.
        dependencies: []
      - name: t8
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of a Dachshund.
        dependencies: []
      - name: t9
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of a Siberian Husky.
        dependencies: []
      - name: t10
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of a Shih Tzu.
        dependencies: []
  - name: tti-sketching-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: <API_URL_HERE>
      successCondition: response.statusCode == 200
      headers:
        Content-Type: application/json
      body: |-
        {
          "prompt": "{{inputs.parameters.prompt}}"
        }
