apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti_Animation_Art
        arguments:
          parameters:
          - name: prompt
            value: Generate an animated image of a high school boy in Japan.
      - name: t2
        template: tti_Animation_Art
        arguments:
          parameters:
          - name: prompt
            value: Generate an animated image of a high school girl in Japan.

      - name: t3
        template: tti_Futuristic_Art
        arguments:
          parameters:
          - name: prompt
            value: Enhance the animated image of the high school boy.
        dependencies: [t1]

      - name: t4
        template: tti_Futuristic_Art
        arguments:
          parameters:
          - name: prompt
            value: Enhance the animated image of the high school girl.
        dependencies: [t2]
      - name: t5
        template: Image_Resizing
        arguments:
          parameters:
          - name: width
            value: 500
          - name: height
            value: 800
          - name: file
            value: '{{tasks.t3.outputs.artifacts.image}}'
        dependencies: [t3]
      - name: t6
        template: Image_Resizing
        arguments:
          parameters:
          - name: width
            value: 500
          - name: height
            value: 800
          - name: file
            value: '{{tasks.t4.outputs.artifacts.image}}'
        dependencies: [t4]

      - name: t7
        template: image_format_converter
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t5.outputs.artifacts.image}}'
          - name: output_format
            value: PNG
        dependencies: [t5]

      - name: t8
        template: image_format_converter
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t6.outputs.artifacts.image}}'
          - name: output_format
            value: JPEG
        dependencies: [t6]

  - name: tti_Animation_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your-api-url/generate_anime_image
      successCondition: response.statusCode == 200

  - name: tti_Futuristic_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your-api-url/generate_futuristic_image
      successCondition: response.statusCode == 200

  - name: Image_Resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://your-api-url/resize_image
      successCondition: response.statusCode == 200

  - name: image_format_converter
    inputs:
      parameters:
      - name: file
      - name: output_format
    http:
      method: POST
      url: http://your-api-url/convert_image
      successCondition: response.statusCode == 200
