apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti-Sketching-Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of the Showa period (1926–1989).
      - name: t2
        template: tti-Sketching-Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of the Jomon period (14,000–300
              BCE).
      - name: t3
        template: tti-Sketching-Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of the Nara period (710–794).
      - name: t4
        template: tti-Sketching-Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of the Heian period (794–1185).
      - name: t5
        template: tti-Sketching-Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of the Kamakura period (1185–1333).
      - name: t6
        template: tti-Sketching-Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of the Muromachi period (1336–1573).
      - name: t7
        template: tti-Sketching-Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of the Azuchi-Momoyama period
              (1573–1603).
      - name: t8
        template: tti-Sketching-Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of the Edo period (1603–1868).
      - name: t9
        template: tti-Sketching-Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of the Meiji period (1868–1912).

  - name: tti-Sketching-Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://example.com/generate_sketching_image/
      headers:
        Content-Type: application/json
      body: '{"prompt": "{{inputs.parameters.prompt}}"}'
      successCondition: response.statusCode == 200
