apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti-Mosaic-Art-Gen
        arguments:
          parameters:
          - name: prompt
            value: The prompt parameter is a user-provided text input in string format
              that serves as the basis for generating a mosaic art style image. It
              is essential for triggering the creation of visually striking mosaic
              compositions based on the user's initial idea or concept.
      - name: t2
        template: tti-Pastel-Art-Gen
        arguments:
          parameters:
          - name: prompt
            value: The prompt parameter is a string data type that serves as a user
              input to guide the generation of a unique pastel art piece using a pre-trained
              model specialized for the pastel art style. It is essential for users
              to provide a creative prompt that influences the artistic output of
              the API, allowing them to translate their ideas into visually appealing
              pastel art images.
      - name: t3
        template: tti-Graffiti-Art-Gen
        arguments:
          parameters:
          - name: prompt
            value: The 'prompt' parameter is a user-provided textual prompt in string
              data type. It serves as the input for the 'tti_Graffiti_Art' API, allowing
              users to input their creative ideas or prompts to generate graffiti-style
              images. This parameter is essential for the API to transform the user's
              textual input into visually appealing graffiti art.
      - name: t4
        template: tti-Mosaic-Art-Enhance
        arguments:
          parameters:
          - name: prompt
            value: The prompt parameter is a user-provided text input in string format
              that serves as the basis for generating a mosaic art style image. It
              is essential for triggering the creation of visually striking mosaic
              compositions based on the user's initial idea or concept.
        dependencies: [t1, t2, t3]
      - name: t5
        template: tti-Mosaic-Art-Resize
        arguments:
          parameters:
          - name: prompt
            value: The prompt parameter is a user-provided text input in string format
              that serves as the basis for generating a mosaic art style image. It
              is essential for triggering the creation of visually striking mosaic
              compositions based on the user's initial idea or concept.
        dependencies: [t1, t2, t3]
      - name: t6
        template: Image-Enhancement
        dependencies: [t1, t2, t3]
      - name: t7
        template: tti-Mosaic-Art-Email
        dependencies: [t4, t5, t6]

  - name: tti-Mosaic-Art-Gen
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://tti-mosaic-art-gen-url
      successCondition: response.statusCode == 200

  - name: tti-Pastel-Art-Gen
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://tti-pastel-art-gen-url
      successCondition: response.statusCode == 200

  - name: tti-Graffiti-Art-Gen
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://tti-graffiti-art-gen-url
      successCondition: response.statusCode == 200

  - name: tti-Mosaic-Art-Enhance
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://tti-mosaic-art-enhance-url
      successCondition: response.statusCode == 200

  - name: tti-Mosaic-Art-Resize
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://tti-mosaic-art-resize-url
      successCondition: response.statusCode == 200

  - name: Image-Enhancement
    http:
      method: POST
      url: http://image-enhancement-url
      successCondition: response.statusCode == 200

  - name: tti-Mosaic-Art-Email
    http:
      method: POST
      url: http://tti-mosaic-art-email-url
      successCondition: response.statusCode == 200
