apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: prompt
    dag:
      tasks:
      - name: t1
        template: tti-animation-art
        arguments:
          parameters:
          - name: prompt
            value: '{{inputs.parameters.prompt}}'
        dependencies: []
      - name: t2
        template: tti-animation-art
        arguments:
          parameters:
          - name: prompt
            value: '{{inputs.parameters.prompt}}'
        dependencies: []
      - name: t3
        template: tti-animation-art
        arguments:
          parameters:
          - name: prompt
            value: '{{inputs.parameters.prompt}}'
        dependencies:
        - t1
        - t2
      - name: t4
        template: tti-futuristic-art
        arguments:
          parameters:
          - name: prompt
            value: Enhanced image of high school girl in futuristic art style
        dependencies:
        - t1
        - t2
      - name: t5
        template: image-resizing
        arguments:
          parameters:
          - name: width
            value: '500'
          - name: height
            value: '800'
          - name: file
            value: '{{tasks.t3.outputs.result}}'  # assuming the output result is an image
        dependencies:
        - t3
        - t4
      - name: t6
        template: image-resizing
        arguments:
          parameters:
          - name: width
            value: '500'
          - name: height
            value: '800'
          - name: file
            value: '{{tasks.t4.outputs.result}}'  # assuming the output result is an image
        dependencies:
        - t3
        - t4
      - name: t7
        template: image-format-converter
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t5.outputs.result}}'
          - name: output_format
            value: PNG
        dependencies:
        - t5
        - t6
      - name: t8
        template: image-format-converter
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t6.outputs.result}}'
          - name: output_format
            value: JPEG
        dependencies:
        - t5
        - t6

  - name: tti-animation-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: /generate_anime_image/
      successCondition: response.statusCode == 200

  - name: tti-futuristic-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: /generate_futuristic_image/
      successCondition: response.statusCode == 200

  - name: image-resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: /resize_image/
      successCondition: response.statusCode == 200

  - name: image-format-converter
    inputs:
      parameters:
      - name: file
      - name: output_format
    http:
      method: POST
      url: /convert_image/
      successCondition: response.statusCode == 200
