apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: width
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: width
    dag:
      tasks:
      - name: t1
        template: tti_Charcoal_Art
        arguments:
          parameters:
          - name: prompt
            value: Renaissance charcoal art prompt    # Example input, replace with actual input
        dependencies: []
      - name: t2
        template: tti_Pastel_Art
        arguments:
          parameters:
          - name: prompt
            value: Baroque pastel art prompt    # Example input, replace with actual input
        dependencies: []
      - name: t3
        template: tti_Painting_Art
        arguments:
          parameters:
          - name: prompt
            value: '{{ tasks.t1.outputs.result }}'
        dependencies: []
      - name: t4
        template: tti_Ukiyo_e_Art
        arguments:
          parameters:
          - name: prompt
            value: '{{ tasks.t1.outputs.result }}'
        dependencies: []
      - name: t5
        template: tti_Charcoal_Art
        arguments:
          parameters:
          - name: prompt
            value: '{{ tasks.t1.outputs.result }}'
        dependencies: [t1, t2, t3, t4]
      - name: t6
        template: tti_Pastel_Art
        arguments:
          parameters:
          - name: prompt
            value: '{{ tasks.t2.outputs.result }}'
        dependencies: [t1, t2, t3, t4]
      - name: t7
        template: tti_Painting_Art
        arguments:
          parameters:
          - name: prompt
            value: '{{ tasks.t3.outputs.result }}'
        dependencies: [t1, t2, t3, t4]
      - name: t8
        template: tti_Ukiyo_e_Art
        arguments:
          parameters:
          - name: prompt
            value: '{{ tasks.t4.outputs.result }}'
        dependencies: [t1, t2, t3, t4]

  - name: tti_Charcoal_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your-api-url.com/generate_charcoal_image/
      successCondition: response.statusCode == 200

  - name: tti_Pastel_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your-api-url.com/generate_pastel_image/
      successCondition: response.statusCode == 200

  - name: tti_Painting_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your-api-url.com/generate_painting_image/
      successCondition: response.statusCode == 200

  - name: tti_Ukiyo_e_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your-api-url.com/generate_ukiyoe_image/
      successCondition: response.statusCode == 200
