apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: A high-quality sketching art style image depicting the Showa period
              (1926–1989), created using the LoRA model and VAE component. The image
              captures the essence of the era with a unique sketching art style, showcasing
              key elements and characteristics of the Showa period.
      - name: t2
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: A high-quality sketching art style image depicting the Jomon period
              (14,000–300 BCE), showcasing intricate details and patterns characteristic
              of that era. The image will capture the essence of Jomon culture through
              a unique artistic interpretation, emphasizing the use of lines, textures,
              and shading to create a visually appealing representation.
      - name: t3
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: A high-quality sketching art style image of the Nara period (710–794),
              created using the LoRA model and VAE component. The image captures the
              essence of the Nara period with intricate details and artistic flair,
              presented in a black and white sketching style.
      - name: t4
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: A high-quality sketching art style image depicting the Heian period
              (794–1185), created using the LoRA model and VAE component. The image
              captures the essence of the historical era with intricate details and
              artistic flair, presented in a black and white sketching art style.
      - name: t5
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: A high-quality sketching art style image depicting the Kamakura
              period (1185–1333), created using the LoRA model and VAE component.
              The image captures the essence of the historical era with intricate
              details and artistic flair, presented in a black and white sketching
              art style.
      - name: t6
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: A high-quality sketching art style image depicting the Muromachi
              period (1336–1573), created using the LoRA model and VAE component.
              The image captures the essence of the historical era with intricate
              details and artistic flair, presented in a black and white sketching
              art style.
      - name: t7
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: A high-quality sketching art style image depicting the Azuchi-Momoyama
              period (1573–1603), created using the LoRA model and VAE component.
              The image captures the essence of the historical era with intricate
              details and artistic flair, presented in a black and white sketch format.
      - name: t8
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: A high-quality sketching art style image depicting the Edo period
              (1603–1868), created using the LoRA model and VAE component. The image
              captures the essence and aesthetics of the Edo period, showcasing intricate
              details and traditional elements characteristic of that era.
      - name: t9
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: A high-quality sketching art style image depicting the Meiji period
              (1868–1912), created using the LoRA model and VAE component. The image
              captures the essence of the historical era with intricate details and
              artistic flair, presented in a black and white sketch format.
  - name: tti_Sketching_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://ai-art-generation-api/tti_Sketching_Art
      successCondition: response.statusCode == 200
