apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: width
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: width
    dag:
      tasks:
      - name: t1
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of a Labrador Retriever.

      - name: t2
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: '{{{{ tasks.t1.result }}}}'
        dependencies: [t1]

      - name: t3
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: '{{{{ tasks.t2.result }}}}'
        dependencies: [t2]

      - name: t4
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: '{{{{ tasks.t3.result }}}}'
        dependencies: [t3]

      - name: t5
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: '{{{{ tasks.t4.result }}}}'
        dependencies: [t4]

      - name: t6
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: '{{{{ tasks.t5.result }}}}'
        dependencies: [t5]

      - name: t7
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: '{{{{ tasks.t6.result }}}}'
        dependencies: [t6]

      - name: t8
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: '{{{{ tasks.t7.result }}}}'
        dependencies: [t7]

      - name: t9
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: '{{{{ tasks.t8.result }}}}'
        dependencies: [t8]

      - name: t10
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: '{{{{ tasks.t9.result }}}}'
        dependencies: [t9]

  - name: tti_Sketching_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: '{{workflow.parameters.width}}'
      successCondition: response.statusCode == 200
