apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: width
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: width
    dag:
      tasks:
      - name: t1
        template: tti-mosaic-art
        arguments:
          parameters:
          - name: prompt
            value: Generate an image of a serene mountain landscape during sunrise
              in mosaic art style.
        dependencies: []

      - name: t2
        template: tti-pastel-art
        arguments:
          parameters:
          - name: prompt
            value: '{{{{ tasks.t1.result }}}}'
        dependencies: [t1]

      - name: t3
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: '{{{{ tasks.t2.result }}}}'
        dependencies: [t2]

      - name: t4
        template: image-resizing
        arguments:
          parameters:
          - name: width
            value: 1920
          - name: height
            value: 1080
          - name: file
            value: '{{{{ tasks.t3.result }}}}'
        dependencies: [t3]

      - name: t5
        template: image-enhancement
        arguments:
          parameters:
          - name: file
            value: '{{{{ tasks.t4.result }}}}'
        dependencies: [t4]

      - name: t6
        template: email-final-art
        arguments:
          parameters:
          - name: file
            value: '{{{{ tasks.t5.result }}}}'
        dependencies: [t5]

  - name: tti-mosaic-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your-service-url/generate_mosaic_image/
      successCondition: response.statusCode == 200

  - name: tti-pastel-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your-service-url/generate_pastel_image/
      successCondition: response.statusCode == 200

  - name: tti-sketching-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your-service-url/generate_sketching_image/
      successCondition: response.statusCode == 200

  - name: image-resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://your-service-url/resize_image/
      successCondition: response.statusCode == 200

  - name: image-enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://your-service-url/image_enhance/
      successCondition: response.statusCode == 200

  - name: email-final-art
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://your-service-url/send_email/
      successCondition: response.statusCode == 200
