apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: width
    - name: height
    - name: prompt
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: width
      - name: height
      - name: prompt
    dag:
      tasks:
      - name: t1
        template: tti-mosaic-art
        arguments:
          parameters:
          - name: prompt
            value: '{{workflow.parameters.prompt}}'
      - name: t2
        template: image-resizing
        arguments:
          parameters:
          - name: width
            value: '{{workflow.parameters.width}}'
          - name: height
            value: '{{workflow.parameters.height}}'
          - name: file
            value: '{{tasks.t1.outputs.result}}'  # Assuming output of t1 is the file
        dependencies: [t1]

  - name: tti-mosaic-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: /generate_mosaic_image/
      headers:
        Content-Type: application/json
      body:
        prompt: '{{inputs.parameters.prompt}}'
      successCondition: response.statusCode == 200
      response:
        body: '{{item}}'

  - name: image-resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: /resize_image/
      headers:
        Content-Type: multipart/form-data
      body:
        width: '{{inputs.parameters.width}}'
        height: '{{inputs.parameters.height}}'
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200
      response:
        body: '{{item}}'
