apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti-Graffiti-Art
        arguments:
          parameters:
          - name: prompt
            value: Urban jungle
      - name: t2
        template: Image-Resizing
        arguments:
          parameters:
          - name: width
            value: '800'
          - name: height
            value: '600'
          - name: file
            value: '{{tasks.t1.outputs.parameters.generated_img}}'
        dependencies: [t1]

  - name: tti-Graffiti-Art
    inputs:
      parameters:
      - name: prompt
    outputs:
      parameters:
      - name: generated_img
        valueFrom:
          path: /generated_img.png
    script:
      image: python:3.8
      command: [python]
      source: |
        from fastapi import FastAPI, HTTPException
        from fastapi.responses import FileResponse
        from PIL import Image
        from diffusers import StableDiffusionPipeline, DPMSolverMultistepScheduler
        import torch
        from pathlib import Path

        app = FastAPI()

        def load_model():
            model_id = 'bakebrain/bergraffi-berlin-graffiti'
            pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16)
            pipe.scheduler = DPMSolverMultistepScheduler.from_config(pipe.scheduler.config)
            pipe = pipe.to('cuda')
            return pipe

        def process_data(prompt, pipe):
            response = pipe(prompt).images[0]
            return response

        @app.post("/generate_grafiti_image/")
        async def generate_image(prompt: str):
            try:
                pipe = load_model()
                prompt = "Grafiti-style picture: " + prompt
                response = process_data(prompt, pipe)
                response.save('/generated_img.png')
                image_path = Path('/generated_img.png')
                if not image_path.is_file():
                    return {"error": "Image not found on the server"}
                return FileResponse(image_path)
            except Exception as e:
                raise HTTPException(status_code=500, detail=str(e))
        if __name__ == "__main__":
            import uvicorn
            uvicorn.run(app, host="0.0.0.0", port=8000)

  - name: Image-Resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    outputs:
      parameters:
      - name: resized_img
        valueFrom:
          path: /resized_image.png
    script:
      image: python:3.8
      command: [python]
      source: |-
        from fastapi import FastAPI, HTTPException, File, UploadFile
        from fastapi.responses import FileResponse
        from PIL import Image
        import io
        import os

        app = FastAPI()

        @app.post('/resize_image/')
        async def resize_image(width: int, height: int, file: UploadFile):
            try:
                contents = await file.read()
                image = Image.open(io.BytesIO(contents))
                resized = image.resize((width, height))
                filename = "/resized_image.png"
                resized.save(filename)
                return FileResponse(filename, media_type="image/png", filename="output.png")
            except Exception as e:
                raise HTTPException(status_code=500, detail=str(e))

        if __name__ == "__main__":
            import uvicorn
            uvicorn.run(app, host="0.0.0.0", port=8000)
