apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: prompt
    - name: width
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: prompt
      - name: width
    dag:
      tasks:
      - name: t1
        template: tti-graffiti-art
        arguments:
          parameters:
          - name: prompt
            value: '{{ inputs.parameters.prompt }}'
        dependencies: []
      - name: t2
        template: image-resizing
        arguments:
          parameters:
          - name: width
            value: '{{ inputs.parameters.width }}'
          - name: height
            value: '{{ tasks.t1.result }}'
          - name: file
            value: '{{ tasks.t1.result }}'
        dependencies:
        - t1
  - name: tti-graffiti-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url:
      successCondition: response.statusCode == 200
  - name: image-resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url:
      successCondition: response.statusCode == 200
