apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: width
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: width
    dag:
      tasks:
      - name: t1
        template: tti-Pastel-Art
        arguments:
          parameters:
          - name: prompt
            value: Create a pastel art image of a sunset over the ocean.
      - name: t2
        template: tti-Pastel-Art
        arguments:
          parameters:
          - name: prompt
            value: '{{{{tasks.t1.result}}}}'
        dependencies: [t1]
      - name: t3
        template: Image-Resizing
        arguments:
          parameters:
          - name: width
            value: 1024
          - name: height
            value: 768
          - name: file
            value: '{{{{tasks.t2.result}}}}'
        dependencies: [t2]
      - name: t4
        template: Image-Enhancement
        arguments:
          parameters:
          - name: file
            value: '{{{{tasks.t3.result}}}}'
        dependencies: [t3]
      - name: t5
        template: Image-Enhancement
        arguments:
          parameters:
          - name: file
            value: '{{{{tasks.t4.result}}}}'
        dependencies: [t4]
  - name: tti-Pastel-Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: <YOUR_URL_HERE>
      successCondition: response.statusCode == 200
  - name: Image-Resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: <YOUR_URL_HERE>
      successCondition: response.statusCode == 200
  - name: Image-Enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: <YOUR_URL_HERE>
      successCondition: response.statusCode == 200
