apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti-Charcoal-Art
        arguments:
          parameters:
          - name: prompt
            value: Create a charcoal art image of a New York landscape in 1990.
        dependencies: []
      - name: t2
        dependencies: [t1]
        template: tti-Charcoal-Art
        arguments:
          parameters:
          - name: prompt
            value: Convert the charcoal art image of the New York landscape in 1990
              to PNG format.
      - name: t3
        dependencies: [t2]
        template: image-resizing
        arguments:
          parameters:
          - name: width
            value: 800
          - name: height
            value: 600
          - name: file
            value: '{{{{tasks.t2.outputs.parameters.artImage}}}}'
      - name: t4
        dependencies: [t3]
        template: image-enhancement
        arguments:
          parameters:
          - name: file
            value: '{{{{tasks.t3.outputs.parameters.resizedImage}}}}'
      - name: t5
        dependencies: [t4]
        template: send-email
        arguments:
          parameters:
          - name: recipient
            value: colleague@example.com
          - name: file
            value: '{{{{tasks.t4.outputs.parameters.enhancedImage}}}}'

  - name: tti-Charcoal-Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://api.charcoalart.com/generate_charcoal_image/
      body:
        prompt: '{{inputs.parameters.prompt}}'
      successCondition: response.statusCode == 200

  - name: image-resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://api.imageresize.com/resize_image/
      body:
        width: '{{inputs.parameters.width}}'
        height: '{{inputs.parameters.height}}'
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200

  - name: image-enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://api.imageenhance.com/image_enhance/
      body:
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200

  - name: send-email
    inputs:
      parameters:
      - name: recipient
      - name: file
    http:
      method: POST
      url: http://api.emailsender.com/send_email/
      body:
        recipient: '{{inputs.parameters.recipient}}'
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200
