apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti-Futuristic-Art
        arguments:
          parameters:
          - name: prompt
            value: Futuristic cityscape at night with neon lights and flying cars.
      - name: t2
        template: Image-Resizing
        arguments:
          parameters:
          - name: width
            value: 1920
          - name: height
            value: 1080
          - name: file
            value: '{{tasks.t1.outputs.artifact.result}}'
        dependencies: [t1]
      - name: t3
        template: Image-Enhancement
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t2.outputs.artifact.result}}'
        dependencies: [t2]
      - name: t4
        template: Image-to-PDF-Conversion
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t3.outputs.artifact.result}}'
        dependencies: [t3]
      - name: t5
        template: Send-PDF-to-Email
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t4.outputs.artifact.result}}'
        dependencies: [t4]

  - name: tti-Futuristic-Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://path.to.tti.futuristic.art
      body: |
        {{
          "prompt": "{{inputs.parameters.prompt}}"
        }}
      successCondition: response.statusCode == 200
      headers:
        Accept: application/json
        Content-Type: application/json

  - name: Image-Resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://path.to.image.resizing
      body: |
        {{
          "width": "{{inputs.parameters.width}}",
          "height": "{{inputs.parameters.height}}",
          "file": "{{inputs.parameters.file}}"
        }}
      successCondition: response.statusCode == 200
      headers:
        Accept: application/json
        Content-Type: application/json

  - name: Image-Enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://path.to.image.enhancement
      body: |
        {{
          "file": "{{inputs.parameters.file}}"
        }}
      successCondition: response.statusCode == 200
      headers:
        Accept: application/json
        Content-Type: application/json

  - name: Image-to-PDF-Conversion
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://path.to.image.to.pdf.conversion
      body: |
        {{
          "file": "{{inputs.parameters.file}}"
        }}
      successCondition: response.statusCode == 200
      headers:
        Accept: application/json
        Content-Type: application/json

  - name: Send-PDF-to-Email
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://path.to.send.pdf.to.email
      body: |
        {{
          "file": "{{inputs.parameters.file}}"
        }}
      successCondition: response.statusCode == 200
      headers:
        Accept: application/json
        Content-Type: application/json
