apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: width
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: width
    dag:
      tasks:
      - name: t1
        template: tti-Sketching-Art
        arguments:
          parameters:
          - name: prompt
            value: Create a sketching art image of a bustling marketplace.
        dependencies: []

      - name: t2
        template: tti-Sketching-Art
        arguments:
          parameters:
          - name: prompt
            value: Convert the sketching art image of a bustling marketplace to a
              PNG format.
        dependencies:
        - t1

      - name: t3
        template: image-resizing
        arguments:
          parameters:
          - name: width
            value: '800'
          - name: height
            value: '600'
          - name: file
            value: '{{tasks.t2.outputs.result}}'
        dependencies:
        - t2

  - name: tti-Sketching-Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://example.com/generate_sketching_image/
      json:
        prompt: '{{inputs.parameters.prompt}}'
      successCondition: response.statusCode == 200

  - name: image-resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://example.com/resize_image/
      headers:
        Content-Type: application/json
      json:
        width: '{{ inputs.parameters.width }}'
        height: '{{ inputs.parameters.height }}'
        file: '{{ inputs.parameters.file }}'
      successCondition: response.statusCode == 200
