apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti_Pastel_Art
        arguments:
          parameters:
          - name: prompt
            value: A serene beach at sunset with palm trees
      - name: t2
        template: convert_to_jpeg
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t1.outputs.artifact}}'
        dependencies: [t1]
      - name: t3
        template: resize_image
        arguments:
          parameters:
          - name: width
            value: 1024
          - name: height
            value: 768
          - name: file
            value: '{{tasks.t2.outputs.artifact}}'
        dependencies: [t2]
      - name: t4
        template: image_enhancement
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t3.outputs.artifact}}'
        dependencies: [t3]
      - name: t5
        template: email_image
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t4.outputs.artifact}}'
        dependencies: [t4]

  - name: tti_Pastel_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your-api-server-url.com/generate_pastel_image/
      body:
        prompt: '{{inputs.parameters.prompt}}'
      successCondition: response.statusCode == 200

  - name: convert_to_jpeg
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://your-api-server-url.com/convert_to_jpeg/
      body:
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200

  - name: resize_image
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://your-api-server-url.com/resize_image/
      body:
        width: '{{inputs.parameters.width}}'
        height: '{{inputs.parameters.height}}'
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200

  - name: image_enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://your-api-server-url.com/image_enhance/
      body:
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200

  - name: email_image
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://your-api-server-url.com/email_image/
      body:
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200
