apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: A castle surrounded by a dense forest
      - name: t2
        template: Image_Resizing
        dependencies: [t1]
        arguments:
          parameters:
          - name: width
            value: 1280
          - name: height
            value: 720
          - name: file
            value: '{{tasks.t1.outputs.art}}'
      - name: t3
        template: Image_Enhancement
        dependencies: [t2]
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t2.outputs.art}}'
      - name: t4
        template: image_to_pdf_conversion
        dependencies: [t3]
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t3.outputs.art}}'
      - name: t5
        template: send_email
        dependencies: [t4]
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t4.outputs.pdf}}'

  - name: tti_Sketching_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://sketching-api-url.com/generate_sketching_image/
      successCondition: response.statusCode == 200
      headers:
        Content-Type: application/json

  - name: Image_Resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://resize-api-url.com/resize_image/
      successCondition: response.statusCode == 200
      headers:
        Content-Type: multipart/form-data

  - name: Image_Enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://enhance-api-url.com/image_enhance/
      successCondition: response.statusCode == 200
      headers:
        Content-Type: multipart/form-data

  - name: image_to_pdf_conversion
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://pdf-convert-api-url.com/convert_to_pdf/
      successCondition: response.statusCode == 200
      headers:
        Content-Type: multipart/form-data

  - name: send_email
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://email-api-url.com/send_email/
      successCondition: response.statusCode == 200
      headers:
        Content-Type: multipart/form-data
