apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: width
    - name: height
    - name: sender
    - name: receiver
    - name: msg_text
    - name: msg_subject
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: width
      - name: height
      - name: sender
      - name: receiver
      - name: msg_text
      - name: msg_subject
    dag:
      tasks:
      - name: t1
        template: tti_Futuristic_Art
        arguments:
          parameters:
          - name: prompt
            value: Create a digital art piece of a futuristic cityscape at night.
        dependencies: []

      - name: t2
        template: image_to_pdf_conversion
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t1.outputs.artwork}}'
        dependencies: [t1]

      - name: t3
        template: Image_Resizing
        arguments:
          parameters:
          - name: width
            value: '{{inputs.parameters.width}}'
          - name: height
            value: '{{inputs.parameters.height}}'
          - name: file
            value: '{{tasks.t2.outputs.pdf}}'
        dependencies: [t2]

      - name: t4
        template: Image_Enhancement
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t3.outputs.resized_image}}'
        dependencies: [t3]

      - name: t5
        template: send_email
        arguments:
          parameters:
          - name: sender
            value: '{{inputs.parameters.sender}}'
          - name: receiver
            value: '{{inputs.parameters.receiver}}'
          - name: msg_text
            value: '{{inputs.parameters.msg_text}}'
          - name: msg_subject
            value: '{{inputs.parameters.msg_subject}}'
          - name: file
            value: '{{tasks.t4.outputs.enhanced_image}}'
        dependencies: [t4]

  - name: tti_Futuristic_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: <URL-ENDPOINT-OF-TTI_FUTURISTIC_ART>
      successCondition: response.statusCode == 200

  - name: image_to_pdf_conversion
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: <URL-ENDPOINT-OF-IMAGE_TO_PDF_CONVERSION>
      successCondition: response.statusCode == 200

  - name: Image_Resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: <URL-ENDPOINT-OF-IMAGE_RESIZING>
      successCondition: response.statusCode == 200

  - name: Image_Enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: <URL-ENDPOINT-OF-IMAGE_ENHANCEMENT>
      successCondition: response.statusCode == 200

  - name: send_email
    inputs:
      parameters:
      - name: sender
      - name: receiver
      - name: msg_text
      - name: msg_subject
      - name: file
    http:
      method: POST
      url: <URL-ENDPOINT-OF-SEND_EMAIL>
      successCondition: response.statusCode == 200
