apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: width
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: width
    dag:
      tasks:
      - name: t1
        template: tti_Futuristic_Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a futuristic image of an iPhone.
        dependencies: []
      - name: t2
        template: Image_Enhancement
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t2.outputs.artifacts.image}}' # Assuming the output of image will be captured as an artifact
        dependencies:
        - t1
      - name: t3
        template: Image_Resizing
        arguments:
          parameters:
          - name: width
            value: 500
          - name: height
            value: 500
          - name: file
            value: '{{tasks.t3.outputs.artifacts.enhanced_image}}'
        dependencies:
        - t2
      - name: t4
        template: Image_Enhancement
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t4.outputs.artifacts.resized_image}}'
        dependencies:
        - t3
      - name: t5
        template: image_to_pdf_conversion
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t5.outputs.artifacts.enhanced_image}}'
        dependencies:
        - t4
      - name: t6
        template: Send_to_John
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t6.outputs.artifacts.pdf_file}}'
        dependencies:
        - t5
      - name: t7
        template: Send_to_Kody
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t7.outputs.artifacts.pdf_file}}'
        dependencies:
        - t6
      - name: t8
        template: Send_to_Mike
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t8.outputs.artifacts.pdf_file}}'
        dependencies:
        - t7

  - name: tti_Futuristic_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: <tti_Futuristic_Art_URL_HERE>
      successCondition: response.statusCode == 200

  - name: Image_Enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: <Image_Enhancement_URL_HERE>
      successCondition: response.statusCode == 200

  - name: Image_Resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: <Image_Resizing_URL_HERE>
      successCondition: response.statusCode == 200

  - name: image_to_pdf_conversion
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: <image_to_pdf_conversion_URL_HERE>
      successCondition: response.statusCode == 200

  - name: Send_to_John
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: <Send_to_John_URL_HERE>
      successCondition: response.statusCode == 200

  - name: Send_to_Kody
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: <Send_to_Kody_URL_HERE>
      successCondition: response.statusCode == 200

  - name: Send_to_Mike
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: <Send_to_Mike_URL_HERE>
      successCondition: response.statusCode == 200
