apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti-animation-art
        arguments:
          parameters:
          - name: prompt
            value: Generate an animated image of a high school boy in Japan.
      - name: t2
        template: tti-animation-art
        arguments:
          parameters:
          - name: prompt
            value: '{{tasks.t1.outputs.prompt}}'
        dependencies: [t1]

      - name: t3
        template: tti-animation-art
        arguments:
          parameters:
          - name: prompt
            value: '{{tasks.t1.outputs.prompt}}'
        dependencies: [t1]
      - name: t4
        template: tti-futuristic-art
        arguments:
          parameters:
          - name: prompt
            value: '{{tasks.t2.outputs.prompt}}'
        dependencies: [t2]
      - name: t5
        template: image-resizing
        arguments:
          parameters:
          - name: width
            value: '500'
          - name: height
            value: '800'
          - name: file
            value: '{{tasks.t3.outputs.result}}'
        dependencies: [t3]
      - name: t6
        template: image-resizing
        arguments:
          parameters:
          - name: width
            value: '500'
          - name: height
            value: '800'
          - name: file
            value: '{{tasks.t4.outputs.result}}'
        dependencies: [t4]
      - name: t7
        template: image-format-converter
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t5.outputs.result}}'
          - name: output_format
            value: PNG
        dependencies: [t5]
      - name: t8
        template: image-format-converter
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t6.outputs.result}}'
          - name: output_format
            value: JPEG
        dependencies: [t6]

  - name: tti-animation-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://animation-art-api/generate_anime_image/
      body:
        prompt: '{{inputs.parameters.prompt}}'
      successCondition: response.statusCode == 200

  - name: tti-futuristic-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://futuristic-art-api/generate_futuristic_image/
      body:
        prompt: '{{inputs.parameters.prompt}}'
      successCondition: response.statusCode == 200

  - name: image-resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://image-resize-api/resize_image/
      body:
        width: '{{inputs.parameters.width}}'
        height: '{{inputs.parameters.height}}'
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200

  - name: image-format-converter
    inputs:
      parameters:
      - name: file
      - name: output_format
    http:
      method: POST
      url: http://image-format-converter-api/convert_image/
      body:
        file: '{{inputs.parameters.file}}'
        output_format: '{{inputs.parameters.output_format}}'
      successCondition: response.statusCode == 200
