apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: width
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: width
    dag:
      tasks:
      - name: t1
        template: tti-ukiyoe-art
        arguments:
          parameters:
          - name: prompt
            value: Depicting the Edo period
      - name: t2
        template: tti-charcoal-art
        arguments:
          parameters:
          - name: prompt
            value: Depicting the Renaissance period
      - name: t3
        template: tti-pastel-art
        arguments:
          parameters:
          - name: prompt
            value: Depicting the Baroque period
      - name: t4
        template: tti-painting-art
        arguments:
          parameters:
          - name: prompt
            value: Depicting the Victorian era
      - name: t5
        template: tti-ukiyoe-art
        arguments:
          parameters:
          - name: prompt
            value: '{{{{ tasks.t1.outputs.result }}}}'
          - name: enhancement
            value: Enhance the quality of the ukiyo-e art style image depicting the
              Edo period.
      - name: t6
        template: tti-charcoal-art
        arguments:
          parameters:
          - name: prompt
            value: '{{{{ tasks.t2.outputs.result }}}}'
          - name: enhancement
            value: Enhance the quality of the charcoal art style image depicting the
              Renaissance period.
      - name: t7
        template: tti-pastel-art
        arguments:
          parameters:
          - name: prompt
            value: '{{{{ tasks.t3.outputs.result }}}}'
          - name: enhancement
            value: Enhance the quality of the pastel art style image depicting the
              Baroque period.
      - name: t8
        template: tti-painting-art
        arguments:
          parameters:
          - name: prompt
            value: '{{{{ tasks.t4.outputs.result }}}}'
          - name: enhancement
            value: Enhance the quality of the painting art style image depicting the
              Victorian era.
  - name: tti-ukiyoe-art
    inputs:
      parameters:
      - name: prompt
      - name: enhancement
    http:
      method: POST
      url: http://your-api-url/generate_ukiyoe_image/
      successCondition: response.statusCode == 200
  - name: tti-charcoal-art
    inputs:
      parameters:
      - name: prompt
      - name: enhancement
    http:
      method: POST
      url: http://your-api-url/generate_charcoal_image/
      successCondition: response.statusCode == 200
  - name: tti-pastel-art
    inputs:
      parameters:
      - name: prompt
      - name: enhancement
    http:
      method: POST
      url: http://your-api-url/generate_pastel_image/
      successCondition: response.statusCode == 200
  - name: tti-painting-art
    inputs:
      parameters:
      - name: prompt
      - name: enhancement
    http:
      method: POST
      url: http://your-api-url/generate_painting_image/
      successCondition: response.statusCode == 200
