apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: width
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: width
    dag:
      tasks:
      - name: t1
        template: tti_sketching_art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art image of an old library.
  - name: tti_sketching_art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your-api-url/generate_sketching_image/
      successCondition: response.statusCode == 200
