apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti_Pastel_Art
        arguments:
          parameters:
          - name: prompt
            value: serene beach at sunset with palm trees
      - name: t2
        template: Image_Conversion
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t1.outputs.result}}'
        dependencies: [t1]
      - name: t3
        template: Image_Resizing
        arguments:
          parameters:
          - name: width
            value: 1024
          - name: height
            value: 768
          - name: file
            value: '{{tasks.t2.outputs.result}}'
        dependencies: [t2]
      - name: t4
        template: Image_Enhancement
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t3.outputs.result}}'
        dependencies: [t3]
      - name: t5
        template: Email_Image
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t4.outputs.result}}'
        dependencies: [t4]

  - name: tti_Pastel_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://example.com/generate_pastel_image
      body: '{"prompt":"{{inputs.parameters.prompt}}"}'
      successCondition: response.statusCode == 200
      output:
        result: /tmp/pastel_art_image.png
  - name: Image_Conversion
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://example.com/convert_image
      body: '{"file":"{{inputs.parameters.file}}"}'
      successCondition: response.statusCode == 200
      output:
        result: /tmp/converted_image.jpg

  - name: Image_Resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://example.com/resize_image
      body: '{"width":{{inputs.parameters.width}}, "height":{{inputs.parameters.height}},
        "file":"{{inputs.parameters.file}}"}'
      successCondition: response.statusCode == 200
      output:
        result: /tmp/resized_image.pdf

  - name: Image_Enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://example.com/enhance_image
      body: '{"file":"{{inputs.parameters.file}}"}'
      successCondition: response.statusCode == 200
      output:
        result: /tmp/enhanced_image.jpg
  - name: Email_Image
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://example.com/email_image
      body: '{"file":"{{inputs.parameters.file}}", "email":"friend@example.com"}'
      successCondition: response.statusCode == 200
