apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: width
    - name: height
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: width
      - name: height
    dag:
      tasks:
      - name: t1
        template: tti-charcoal-art
        arguments:
          parameters:
          - name: prompt
            value: Create a charcoal art image of a New York landscape in 1990.
        dependencies: []
      - name: t2
        template: tti-charcoal-art
        arguments:
          parameters:
          - name: prompt
            value: Convert the charcoal art image of the New York landscape in 1990
              to PNG format.
        dependencies:
        - t1
      - name: t3
        template: image-resizing
        arguments:
          parameters:
          - name: width
            value: '{{inputs.parameters.width}}'
          - name: height
            value: '{{inputs.parameters.height}}'
          - name: file
            value: '{{tasks.t2.outputs.result}}'
        dependencies:
        - t2
      - name: t4
        template: image-enhancement
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t3.outputs.result}}'
        dependencies:
        - t3
      - name: t5
        template: email-sending
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t4.outputs.result}}'
          - name: email
            value: colleague@example.com
        dependencies:
        - t4
  - name: tti-charcoal-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: <URL for the charcoal art generation API>
      successCondition: response.statusCode == 200
  - name: image-resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: <URL for the image resizing API>
      successCondition: response.statusCode == 200
  - name: image-enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: <URL for the image enhancement API>
      successCondition: response.statusCode == 200
  - name: email-sending
    inputs:
      parameters:
      - name: file
      - name: email
    http:
      method: POST
      url: <URL for the email sending API>
      successCondition: response.statusCode == 200
