apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: width
      - name: height
      - name: sender
      - name: receiver
      - name: msg_text
      - name: msg_subject
    dag:
      tasks:
      - name: t1
        template: tti-Futuristic-Art
        arguments:
          parameters:
          - name: prompt
            value: Futuristic cityscape at night
        dependencies: []
      - name: t2
        template: image_to_pdf_conversion
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t1.outputs.art_image}}'
        dependencies:
        - t1
      - name: t3
        template: image_resizing
        arguments:
          parameters:
          - name: width
            value: '{{workflow.parameters.width}}'
          - name: height
            value: '{{workflow.parameters.height}}'
          - name: file
            value: '{{tasks.t2.outputs.pdf_file}}'
        dependencies:
        - t2
      - name: t4
        template: image_enhancement
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t3.outputs.resized_image}}'
        dependencies:
        - t3
      - name: t5
        template: send_email
        arguments:
          parameters:
          - name: sender
            value: '{{workflow.parameters.sender}}'
          - name: receiver
            value: '{{workflow.parameters.receiver}}'
          - name: msg_text
            value: '{{workflow.parameters.msg_text}}'
          - name: msg_subject
            value: '{{workflow.parameters.msg_subject}}'
          - name: file
            value: '{{tasks.t4.outputs.enhanced_image}}'
        dependencies:
        - t4
  - name: tti-Futuristic-Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://example.com/generate_futuristic_image
      successCondition: response.statusCode == 200
    outputs:
      parameters:
      - name: art_image
        valueFrom:
          path: /path/to/generated_img.png

  - name: image_to_pdf_conversion
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://example.com/convert_to_pdf
      successCondition: response.statusCode == 200
    outputs:
      parameters:
      - name: pdf_file
        valueFrom:
          path: /path/to/output.pdf

  - name: image_resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://example.com/resize_image
      successCondition: response.statusCode == 200
    outputs:
      parameters:
      - name: resized_image
        valueFrom:
          path: /path/to/output.png

  - name: image_enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://example.com/image_enhance
      successCondition: response.statusCode == 200
    outputs:
      parameters:
      - name: enhanced_image
        valueFrom:
          path: /path/to/enhanced_image.jpg

  - name: send_email
    inputs:
      parameters:
      - name: sender
      - name: receiver
      - name: msg_text
      - name: msg_subject
      - name: file
    http:
      method: POST
      url: http://example.com/send_email
      successCondition: response.statusCode == 200
    outputs:
      parameters:
      - name: email_status
        valueFrom:
          path: /path/to/email/status
