apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: A castle surrounded by a dense forest
      - name: t2
        dependencies: [t1]
        template: Image_Resizing
        arguments:
          parameters:
          - name: width
            value: 1280
          - name: height
            value: 720
          - name: file
            value: '{{tasks.t1.outputs.artifacts.generated_img}}'
      - name: t3
        dependencies: [t2]
        template: Image_Enhancement
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t2.outputs.artifacts.resized_image}}'
      - name: t4
        dependencies: [t3]
        template: image_to_pdf_conversion
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t3.outputs.artifacts.enhanced_image}}'
      - name: t5
        dependencies: [t4]
        template: Send_PDF
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t4.outputs.artifacts.converted_pdf}}'
  - name: tti_Sketching_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://example.com/generate_sketching_image
      successCondition: response.statusCode == 200
      body:
        prompt: '{{inputs.parameters.prompt}}'

  - name: Image_Resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://example.com/resize_image
      successCondition: response.statusCode == 200
      body:
        width: '{{inputs.parameters.width}}'
        height: '{{inputs.parameters.height}}'
        file: '{{inputs.parameters.file}}'
  - name: Image_Enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://example.com/image_enhance
      successCondition: response.statusCode == 200
      body:
        file: '{{inputs.parameters.file}}'

  - name: image_to_pdf_conversion
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://example.com/convert_to_pdf
      successCondition: response.statusCode == 200
      body:
        file: '{{inputs.parameters.file}}'

  - name: Send_PDF
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://example.com/send_pdf
      successCondition: response.statusCode == 200
      body:
        file: '{{inputs.parameters.file}}'
