apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters: []
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters: []
    dag:
      tasks:
      - name: t1
        template: tti-pastel-art
        arguments:
          parameters:
          - name: prompt
            value: '{{ tasks.t1.result }}'
        dependencies: []
      - name: t2
        template: image-enhancement
        arguments:
          parameters:
          - name: file
            value: '{{ tasks.t1.result }}'
        dependencies:
        - t1
      - name: t3
        template: tti-pastel-art
        arguments:
          parameters: []
        dependencies:
        - t2
  - name: tti-pastel-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url:
      successCondition: response.statusCode == 200
  - name: image-enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url:
      successCondition: response.statusCode == 200
