apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: graffiti-resize-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti-graffiti-art
        arguments:
          parameters:
          - name: prompt
            value: Urban jungle
      - name: t2
        dependencies: [t1]
        template: image-resizing
        arguments:
          parameters:
          - name: width
            value: '800'
          - name: height
            value: '600'
          - name: file
            value: '{{tasks.t1.outputs.result}}'

  - name: tti-graffiti-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your-graffiti-api-endpoint/generate_grafiti_image/
      headers:
        Content-Type: application/json
      body:
        prompt: '{{inputs.parameters.prompt}}'
      output:
        name: result
        path: /tmp/generated_img.png
      successCondition: response.statusCode == 200
      failureCondition: response.statusCode != 200

  - name: image-resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://your-resizing-api-endpoint/resize_image/
      headers:
        Content-Type: application/json
      body:
        width: '{{inputs.parameters.width}}'
        height: '{{inputs.parameters.height}}'
        file: '{{inputs.parameters.file}}'
      output:
        name: result
        path: /tmp/resized_image.png
      successCondition: response.statusCode == 200
      failureCondition: response.statusCode != 200
