apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: prompt
  entrypoint: main
  templates:
  - name: main
    inputs:
    parameters:
    - name: prompt
    dag:
      tasks:
      - name: t1
        template: tti_charcoal_art
        arguments:
          parameters:
          - name: prompt
            value: '{{inputs.parameters.prompt}}'
        dependencies: []
  - name: tti_charcoal_art
    inputs:
    parameters:
    - name: prompt
    http:
      method: POST
      url: http://path-to-your-api/generate_charcoal_image/    # Placeholder URL, update with actual endpoint
      headers:
        Content-Type: application/json
      body: |
        {
          "prompt": "{{inputs.parameters.prompt}}"
        }
      successCondition: response.statusCode == 200
      response:
        jsonPath: .file  # Update according to actual response structure if different
