apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti-mosaic-art
        arguments:
          parameters:
          - name: prompt
            value: Ancient Roman architecture
      - name: t2
        dependencies: [t1]
        template: resize-image
        arguments:
          parameters:
          - name: width
            value: '1024'
          - name: height
            value: '768'
          - name: file
            value: '{{tasks.t1.outputs.artifacts.generated_image}}'

  - name: tti-mosaic-art
    inputs:
      parameters:
      - name: prompt
    outputs:
      artifacts:
      - name: generated_image
        path: /mnt/data/generated_img.png
    container:
      image: python:3.8
      command: [python, -c]
      args:
      - |
        import requests
        from PIL import Image
        from io import BytesIO

        url = "http://tti_mosaic_art_server/generate_mosaic_image/"
        prompt = "{{inputs.parameters.prompt}}"
        response = requests.post(url, json={"prompt": f"Mosaic-style picture: {prompt}"})
        image = Image.open(BytesIO(response.content))
        image.save("/mnt/data/generated_img.png")
    volumeMounts:
    - mountPath: /mnt/data
      name: workdir

  - name: resize-image
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    container:
      image: python:3.8
      command: [python, -c]
      args:
      - |
        from PIL import Image
        import requests

        width = int("{{inputs.parameters.width}}")
        height = int("{{inputs.parameters.height}}")
        file_url = "{{inputs.parameters.file}}"
        response = requests.get(file_url)
        image = Image.open(BytesIO(response.content))
        resized_image = image.resize((width, height))
        resized_image.save("/mnt/data/resized_image.png")
    volumeMounts:
    - mountPath: /mnt/data
      name: workdir

  volumes:
  - name: workdir
    emptyDir: {}
