apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti_charcoal_art
        arguments:
          parameters:
          - name: prompt
            value: Generate a charcoal art image of a serene forest.

  - name: tti_charcoal_art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: <insert-api-url-here> # Replace with the actual URL
      successCondition: response.statusCode == 200
