apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: prompt
      value: A futuristic cityscape at night
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: prompt
    dag:
      tasks:
      - name: t1
        template: tti_futuristic_art
        arguments:
          parameters:
          - name: prompt
            value: '{{inputs.parameters.prompt}}'
      - name: t2
        template: image_to_pdf_conversion
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t1.outputs.art}}'
        dependencies: [t1]

  - name: tti_futuristic_art
    inputs:
      parameters:
      - name: prompt
    outputs:
      parameters:
      - name: art
        valueFrom:
          jsonPath: '{.outputs.result_file}'
    http:
      method: POST
      url: http://your-api-endpoint.com/generate_futuristic_image/
      headers:
        Content-Type: application/json
      body:
        prompt: '{{inputs.parameters.prompt}}'
      successCondition: response.statusCode == 200

  - name: image_to_pdf_conversion
    inputs:
      parameters:
      - name: file
    outputs:
      parameters:
      - name: pdf
        valueFrom:
          jsonPath: '{.outputs.result_file}'
    http:
      method: POST
      url: http://your-api-endpoint.com/convert_to_pdf/
      headers:
        Content-Type: multipart/form-data
      body:
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200
