apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: prompt
    dag:
      tasks:
      - name: t1
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: '{{inputs.parameters.prompt}}'

  - name: tti-sketching-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: '{{workflow.parameters.url}}/generate_sketching_image/'
      headers:
        Content-Type: application/json
      body: |
        {
          "prompt": "{{inputs.parameters.prompt}}"
        }
      successCondition: response.statusCode == 200
