apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti-animation-art
        arguments:
          parameters:
          - name: prompt
            value: High school boy in Japan with cherry blossoms and traditional architecture
      - name: t2
        template: tti-animation-art
        arguments:
          parameters:
          - name: prompt
            value: High school girl in Japan with school uniform and cultural elements
      - name: t3
        template: tti-animation-art
        arguments:
          parameters:
          - name: prompt
            value: '{{tasks.t1.outputs.result}}'
        dependencies: [t1, t2]
      - name: t4
        template: tti-futuristic-art
        arguments:
          parameters:
          - name: prompt
            value: '{{tasks.t2.outputs.result}}'
        dependencies: [t1, t2]
      - name: t5
        template: image-resizing
        arguments:
          parameters:
          - name: width
            value: 500
          - name: height
            value: 800
          - name: file
            value: '{{tasks.t3.outputs.result}}'
        dependencies: [t3, t4]
      - name: t6
        template: image-resizing
        arguments:
          parameters:
          - name: width
            value: 500
          - name: height
            value: 800
          - name: file
            value: '{{tasks.t4.outputs.result}}'
        dependencies: [t3, t4]
      - name: t7
        template: image-format-converter
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t5.outputs.result}}'
          - name: output_format
            value: PNG
        dependencies: [t5, t6]
      - name: t8
        template: image-format-converter
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t6.outputs.result}}'
          - name: output_format
            value: JPEG
        dependencies: [t5, t6]

  - name: tti-animation-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your-animation-api-url/generate_anime_image/
      successCondition: response.statusCode == 200

  - name: tti-futuristic-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your-futuristic-api-url/generate_futuristic_image/
      successCondition: response.statusCode == 200

  - name: image-resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://your-image-resizing-api-url/resize_image/
      successCondition: response.statusCode == 200

  - name: image-format-converter
    inputs:
      parameters:
      - name: file
      - name: output_format
    http:
      method: POST
      url: http://your-image-format-converter-api-url/convert_image/
      successCondition: response.statusCode == 200
