apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of a Labrador Retriever.
      - name: t2
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of a German Shepherd.
      - name: t3
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of a Golden Retriever.
      - name: t4
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of a Bulldog.
      - name: t5
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of a Poodle.
      - name: t6
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of a Beagle.
      - name: t7
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of a Rottweiler.
      - name: t8
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of a Dachshund.
      - name: t9
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of a Siberian Husky.
      - name: t10
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image of a Shih Tzu.
  - name: tti_Sketching_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://example.com/generate_sketching_image/
      headers:
        Content-Type: application/json
      body: '{"prompt": "{{ inputs.parameters.prompt }}"}'
      successCondition: response.statusCode == 200
