apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image depicting technological advancements
              of computers in the early 1900s.
      - name: t2
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: Generate a sketching art style image depicting technological advancements
              of computers in the 1950s.
      - name: t3
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: Generate a futuristic art style image depicting technological advancements
              of computers in the 2020s.
      - name: t4
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: Convert the sketching art style image of the early 1900s to PNG
              format.
        dependencies: [t1]
      - name: t5
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: Convert the sketching art style image of the 1950s to PNG format.
        dependencies: [t2]
      - name: t6
        template: tti-futuristic-art
        arguments:
          parameters:
          - name: prompt
            value: Convert the futuristic art style image of the 2020s to PNG format.
        dependencies: [t3]
      - name: t7
        template: tti-sketching-art-mail
        arguments:
          parameters:
          - name: prompt
            value: Email the PNG format image of the 2020s to the project supervisor.
        dependencies: [t6]

  - name: tti-sketching-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: /generate_sketching_image/
      successCondition: response.statusCode == 200

  - name: tti-futuristic-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: /generate_futuristic_image/
      successCondition: response.statusCode == 200

  - name: tti-sketching-art-mail
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: /send_mail_image/
      successCondition: response.statusCode == 200
