apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti_Futuristic_Art
        arguments:
          parameters:
          - name: prompt
            value: A digital art piece of a futuristic cityscape at night, with neon
              lights and flying cars.
      - name: t2
        dependencies: [t1]
        template: Image_Resizing
        arguments:
          parameters:
          - name: width
            value: 1920
          - name: height
            value: 1080
          - name: file
            value: '{{{{ tasks.t1.outputs.artifact.file }}}}'
      - name: t3
        dependencies: [t2]
        template: Image_Enhancement
        arguments:
          parameters:
          - name: file
            value: '{{{{ tasks.t2.outputs.artifact.file }}}}'
      - name: t4
        dependencies: [t3]
        template: image_to_pdf_conversion
        arguments:
          parameters:
          - name: file
            value: '{{{{ tasks.t3.outputs.artifact.file }}}}'
      - name: t5
        dependencies: [t4]
        template: image_to_pdf_conversion
        arguments:
          parameters:
          - name: file
            value: '{{{{ tasks.t4.outputs.artifact.file }}}}'
  - name: tti_Futuristic_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url:   # URL to the endpoint of the tti_Futuristic_Art API
      successCondition: response.statusCode == 200
      body: '{"prompt": "{{ inputs.parameters.prompt }}"}'
      output:
        artifact:
          name: file
          path: /tmp/output
  - name: Image_Resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url:   # URL to the endpoint of the Image_Resizing API
      successCondition: response.statusCode == 200
      body: '{"width": {{ inputs.parameters.width }}, "height": {{ inputs.parameters.height
        }}, "file": "{{ inputs.parameters.file }}"}'
      output:
        artifact:
          name: file
          path: /tmp/output
  - name: Image_Enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url:   # URL to the endpoint of the Image_Enhancement API
      successCondition: response.statusCode == 200
      body: '{"file": "{{ inputs.parameters.file }}"}'
      output:
        artifact:
          name: file
          path: /tmp/output
  - name: image_to_pdf_conversion
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url:   # URL to the endpoint of the image_to_pdf_conversion API
      successCondition: response.statusCode == 200
      body: '{"file": "{{ inputs.parameters.file }}"}'
      output:
        artifact:
          name: file
          path: /tmp/output
