apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: width
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: width
    dag:
      tasks:
      - name: t1
        template: tti-pastel-art
        arguments:
          parameters:
          - name: prompt
            value: Create a pastel art image of a serene beach at sunset with palm
              trees.
        dependencies: []
      - name: t2
        template: convert-to-jpeg
        arguments:
          parameters:
          - name: prompt
            value: '{{tasks.t1.result}}'
        dependencies:
        - t1
      - name: t3
        template: resize-image
        arguments:
          parameters:
          - name: width
            value: '{{workflow.parameters.width}}'
          - name: height
            value: '768'
          - name: file
            value: '{{tasks.t2.result}}'
        dependencies:
        - t2
      - name: t4
        template: enhance-image
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t3.result}}'
        dependencies:
        - t3
      - name: t5
        template: email-image
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t4.result}}'
        dependencies:
        - t4

  - name: tti-pastel-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://example.com/generate_pastel_image/
      headers:
        Content-Type: application/json
      body: |
        {
          "prompt": "{{inputs.parameters.prompt}}"
        }
      successCondition: response.statusCode == 200

  - name: convert-to-jpeg
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://example.com/convert_to_jpeg/
      headers:
        Content-Type: application/json
      body: |
        {
          "prompt": "{{inputs.parameters.prompt}}"
        }
      successCondition: response.statusCode == 200

  - name: resize-image
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://example.com/resize_image/
      headers:
        Content-Type: multipart/form-data
      body: |
        {
          "width": "{{inputs.parameters.width}}",
          "height": "{{inputs.parameters.height}}",
          "file": "{{inputs.parameters.file}}"
        }
      successCondition: response.statusCode == 200

  - name: enhance-image
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://example.com/image_enhance/
      headers:
        Content-Type: multipart/form-data
      body: |
        {
          "file": "{{inputs.parameters.file}}"
        }
      successCondition: response.statusCode == 200

  - name: email-image
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://example.com/email_image/
      headers:
        Content-Type: multipart/form-data
      body: |
        {
          "file": "{{inputs.parameters.file}}"
        }
      successCondition: response.statusCode == 200
