apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: A castle surrounded by a dense forest
      - name: t2
        template: image-resizing
        arguments:
          parameters:
          - name: width
            value: '1280'
          - name: height
            value: '720'
          - name: file
            value: '{{tasks.t1.outputs.parameters.output}}'
        dependencies: [t1]
      - name: t3
        template: image-enhancement
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t2.outputs.parameters.output}}'
        dependencies: [t2]
      - name: t4
        template: image-to-pdf-conversion
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t3.outputs.parameters.output}}'
        dependencies: [t3]
      - name: t5
        template: email-pdf
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t4.outputs.parameters.output}}'
        dependencies: [t4]
  - name: tti-sketching-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your-api-endpoint/generate_sketching_image
      successCondition: response.statusCode == 200
  - name: image-resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://your-api-endpoint/resize_image
      successCondition: response.statusCode == 200
  - name: image-enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://your-api-endpoint/image_enhance
      successCondition: response.statusCode == 200
  - name: image-to-pdf-conversion
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://your-api-endpoint/convert_to_pdf
      successCondition: response.statusCode == 200
  - name: email-pdf
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://your-api-endpoint/send_email
      successCondition: response.statusCode == 200
