apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti-futuristic-art
        arguments:
          parameters:
          - name: prompt
            value: Create a digital art piece of a futuristic cityscape.
        dependencies: []

      - name: t2
        template: tti-pastel-art
        arguments:
          parameters:
          - name: prompt
            value: '{{tasks.t1.outputs.result}}'
        dependencies: [t1]

      - name: t3
        template: image-resizing
        arguments:
          parameters:
          - name: width
            value: 1024    # Replace with the desired width
          - name: height
            value: 768     # Replace with the desired height
          - name: file
            value: '{{tasks.t2.outputs.result}}'
        dependencies: [t2]

  - name: tti-futuristic-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://localhost:8000/generate_futuristic_image/    # Replace with actual URL
      headers:
        Content-Type: application/json
      body: |
        {
          "prompt": "{{inputs.parameters.prompt}}"
        }
      successCondition: response.statusCode == 200

  - name: tti-pastel-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://localhost:8001/generate_pastel_image/    # Replace with actual URL
      headers:
        Content-Type: application/json
      body: |
        {
          "prompt": "{{inputs.parameters.prompt}}"
        }
      successCondition: response.statusCode == 200

  - name: image-resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://localhost:8002/resize_image/    # Replace with actual URL
      headers:
        Content-Type: multipart/form-data
      body: |
        {
          "width": {{inputs.parameters.width}},
          "height": {{inputs.parameters.height}},
          "file": "{{inputs.parameters.file}}"
        }
      successCondition: response.statusCode == 200
