apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: width
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: width
    dag:
      tasks:
      - name: t1
        template: tti-futuristic-art
        arguments:
          parameters:
          - name: prompt
            value: Create a digital art piece of a futuristic cityscape at night.
        dependencies: []
      - name: t2
        template: image-to-pdf
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t1.outputs.result}}'
        dependencies: [t1]
      - name: t3
        template: image-resizing
        arguments:
          parameters:
          - name: width
            value: '{{workflow.parameters.width}}'
          - name: height
            value: '1080'
          - name: file
            value: '{{tasks.t2.outputs.result}}'
        dependencies: [t2]
      - name: t4
        template: image-enhancement
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t3.outputs.result}}'
        dependencies: [t3]
      - name: t5
        template: send-email
        arguments:
          parameters:
          - name: sender
            value: example_sender@example.com
          - name: receiver
            value: example_receiver@example.com
          - name: msg_text
            value: Please find attached the enhanced PDF of the futuristic cityscape
              at night.
          - name: msg_subject
            value: Enhanced PDF of Futuristic Cityscape
          - name: file
            value: '{{tasks.t4.outputs.result}}'
        dependencies: [t4]

  - name: tti-futuristic-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: /generate_futuristic_image/
      successCondition: response.statusCode == 200

  - name: image-to-pdf
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: /convert_to_pdf/
      successCondition: response.statusCode == 200

  - name: image-resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: /resize_image/
      successCondition: response.statusCode == 200

  - name: image-enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: /image_enhance/
      successCondition: response.statusCode == 200

  - name: send-email
    inputs:
      parameters:
      - name: sender
      - name: receiver
      - name: msg_text
      - name: msg_subject
      - name: file
    http:
      method: POST
      url: /send_email/
      successCondition: response.statusCode == 200
