apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti_charcoal_art
        arguments:
          parameters:
          - name: prompt
            value: Generate a charcoal art image of a serene forest.
      - name: t2
        template: image_resizing
        arguments:
          parameters:
          - name: width
            value: 1920
          - name: height
            value: 1080
          - name: file
            value: '{{tasks.t1.outputs.result}}'
        dependencies: [t1]
      - name: t3
        template: image_to_pdf_conversion
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t2.outputs.result}}'
        dependencies: [t2]

  - name: tti_charcoal_art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://example.com/generate_charcoal_image/  # Replace with actual URL for the tti_Charcoal_Art API
      headers:
        Content-Type: application/json
      body: |
        {
          "prompt": "{{inputs.parameters.prompt}}"
        }
      successCondition: response.statusCode == 200

  - name: image_resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://example.com/resize_image/  # Replace with actual URL for the Image_Resizing API
      headers:
        Content-Type: application/json
      body: |
        {
          "width": {{inputs.parameters.width}},
          "height": {{inputs.parameters.height}},
          "file": "{{inputs.parameters.file}}"
        }
      successCondition: response.statusCode == 200

  - name: image_to_pdf_conversion
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://example.com/convert_to_pdf/  # Replace with actual URL for the image_to_pdf_conversion API
      headers:
        Content-Type: application/json
      body: |
        {
          "file": "{{inputs.parameters.file}}"
        }
      successCondition: response.statusCode == 200
