apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: prompt
      value: A bustling marketplace
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: prompt
    dag:
      tasks:
      - name: t1
        template: tti-sketching-art
        arguments:
          parameters:
          - name: prompt
            value: '{{inputs.parameters.prompt}}'
        dependencies: []
      - name: t2
        template: image-to-pdf-conversion
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t1.outputs.result}}'
        dependencies: [t1]

  - name: tti-sketching-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: <your_sketching_art_api_url_here>
      headers:
        Content-Type: application/json
      body:
        prompt: '{{inputs.parameters.prompt}}'
      successCondition: response.statusCode == 200
      output:
        result: response.body.result

  - name: image-to-pdf-conversion
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: <your_image_to_pdf_api_url_here>
      headers:
        Content-Type: multipart/form-data
      body:
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200
      output:
        result: response.body.result
