apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti_futuristic_art
        arguments:
          parameters:
          - name: prompt
            value: '{{workflow.parameters.prompt}}'
  - name: tti_futuristic_art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://path-to-your-api/generate_futuristic_image/  # Replace with the actual URL for the 'tti_Futuristic_Art' API
      headers:
        Content-Type: application/json
      body: |
        {
          "prompt": "{{inputs.parameters.prompt}}"
        }
      successCondition: response.statusCode == 200
