apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti_Mosaic_Art
        arguments:
          parameters:
          - name: prompt
            value: Ancient Roman architecture
      - name: t2
        dependencies: [t1]
        template: Image_Resizing
        arguments:
          parameters:
          - name: width
            value: '1024'
          - name: height
            value: '768'
          - name: file
            value: '{{ tasks.t1.outputs.artifact.myfile }}'

  - name: tti_Mosaic_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: '{{workflow.parameters.url}}/generate_mosaic_image/'
      headers:
        Content-Type: application/json
      body: '{"prompt": "{{inputs.parameters.prompt}}"}'
      successCondition: success

  - name: Image_Resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: '{{workflow.parameters.url}}/resize_image/'
      headers:
        Content-Type: multipart/form-data
      formData:
        width: '{{inputs.parameters.width}}'
        height: '{{inputs.parameters.height}}'
        file: '{{inputs.parameters.file}}'
      successCondition: success
