apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: width
      value: '900'   # Example width value; adjust as needed
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: width
    dag:
      tasks:
      - name: t1
        template: tti-pastel-art
        arguments:
          parameters:
          - name: prompt
            value: A beautiful pastel art image depicting a sunset over the ocean.
        dependencies: []

  - name: tti-pastel-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: '{{ .input.parameters.prompt }}'
      body:
        prompt: '{{ .inputs.parameters.prompt }}'
      successCondition: response.statusCode == 200
      output:
        artifact:
          name: generated-image
          path: /tmp/generated_image.png
