apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: prompt
      value: Urban jungle
    - name: width
      value: 800
    - name: height
      value: 600
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: prompt
      - name: width
      - name: height
    dag:
      tasks:
      - name: t1
        template: tti-Graffiti-Art
        arguments:
          parameters:
          - name: prompt
            value: '{{inputs.parameters.prompt}}'
        dependencies: []
      - name: t2
        template: image-resizing
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t1.outputs.result}}' # Output from t1 used as an input for t2
          - name: width
            value: '{{inputs.parameters.width}}'
          - name: height
            value: '{{inputs.parameters.height}}'
        dependencies: [t1]

  - name: tti-Graffiti-Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your-graffiti-art-api-endpoint.com/generate_grafiti_image/ # Replace with the actual URL
      successCondition: response.statusCode == 200
      headers:
        Content-Type: application/json
      body: |
        {
          "prompt": "{{inputs.parameters.prompt}}"
        }

  - name: image-resizing
    inputs:
      parameters:
      - name: file
      - name: width
      - name: height
    http:
      method: POST
      url: http://your-image-resizing-api-endpoint.com/resize_image/ # Replace with the actual URL
      successCondition: response.statusCode == 200
      headers:
        Content-Type: application/json
      body: |-
        {
          "width": "{{inputs.parameters.width}}",
          "height": "{{inputs.parameters.height}}",
          "file": "{{inputs.parameters.file}}"
        }
