apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti_sketching_art
        arguments:
          parameters:
          - name: prompt
            value: A bustling marketplace full of vibrant activity.
        dependencies: []

      - name: t2
        template: tti_sketching_art
        arguments:
          parameters:
          - name: prompt
            value: '{{tasks.t1.outputs.result}}'
        dependencies: [t1]

      - name: t3
        template: image_resizing
        arguments:
          parameters:
          - name: width
            value: 800
          - name: height
            value: 600
          - name: file
            value: '{{tasks.t2.outputs.result}}'
        dependencies: [t2]

  - name: tti_sketching_art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://sketching-art-service/generate_sketching_image
      successCondition: response.statusCode == 200

  - name: image_resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://image-resizing-service/resize_image
      successCondition: response.statusCode == 200
