apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: t1
        template: tti-Futuristic-Art
        arguments:
          parameters:
          - name: prompt
            value: Create a digital art piece of a futuristic cityscape.
        dependencies: []
      - name: t2
        template: tti-Pastel-Art
        arguments:
          parameters:
          - name: prompt
            value: '{{{{ tasks.t1.result }}}}'
        dependencies:
        - t1
      - name: t3
        template: Image-Resizing
        arguments:
          parameters:
          - name: width
            value: '800' # Example width, adjust as necessary
          - name: height
            value: '600' # Example height, adjust as necessary
          - name: file
            value: '{{{{ tasks.t2.result }}}}'
        dependencies:
        - t2

  - name: tti-Futuristic-Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your.api.endpoint/tti_futuristic_art
      successCondition: response.statusCode == 200

  - name: tti-Pastel-Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://your.api.endpoint/tti_pastel_art
      successCondition: response.statusCode == 200

  - name: Image-Resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://your.api.endpoint/image_resizing
      successCondition: response.statusCode == 200
