apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: width
    - name: height
    - name: prompt
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: width
      - name: height
      - name: prompt
    dag:
      tasks:
      - name: t1
        template: tti-pastel-art
        arguments:
          parameters:
          - name: prompt
            value: '{{inputs.parameters.prompt}}'
      - name: t2
        template: convert-to-jpeg
        arguments:
          parameters:
          - name: prompt
            value: '{{inputs.parameters.prompt}}'
        dependencies: [t1]
      - name: t3
        template: resize-image
        arguments:
          parameters:
          - name: width
            value: '{{inputs.parameters.width}}'
          - name: height
            value: '{{inputs.parameters.height}}'
          - name: file
            value: '{{tasks.t2.outputs.result}}'
        dependencies: [t2]
      - name: t4
        template: enhance-image
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t3.outputs.result}}'
        dependencies: [t3]
      - name: t5
        template: send-email
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t4.outputs.result}}'
        dependencies: [t4]
  - name: tti-pastel-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: [replace_with_actual_url_for_tti_pastel_art]
      successCondition: response.statusCode == 200
  - name: convert-to-jpeg
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: [replace_with_actual_url_for_convert_to_jpeg]
      successCondition: response.statusCode == 200
  - name: resize-image
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: [replace_with_actual_url_for_resize_image]
      successCondition: response.statusCode == 200
  - name: enhance-image
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: [replace_with_actual_url_for_enhance_image]
      successCondition: response.statusCode == 200
  - name: send-email
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: [replace_with_actual_url_for_send_email]
      successCondition: response.statusCode == 200
