apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: prompt
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: prompt
    dag:
      tasks:
      - name: t1
        template: tti-Pastel-Art
        arguments:
          parameters:
          - name: prompt
            value: '{{inputs.parameters.prompt}}'
        dependencies: []
      - name: t2
        template: Image-Enhancement
        arguments:
          parameters:
          - name: file
            value: '{{tasks.t1.outputs.result}}'
        dependencies: [t1]
      - name: t3
        template: tti-Pastel-Art
        arguments:
          parameters:
          - name: prompt
            value: '{{tasks.t2.outputs.result}}'
        dependencies: [t2]

  - name: tti-Pastel-Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: /generate_pastel_image/
      successCondition: response.statusCode == 200

  - name: Image-Enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: /image_enhance/
      successCondition: response.statusCode == 200
