apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: width
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: width
    dag:
      tasks:
      - name: t1
        template: tti-charcoal-art
        arguments:
          parameters:
          - name: prompt
            value: Create a charcoal art image of a New York landscape in 1990.
        dependencies: []
      - name: t2
        template: tti-charcoal-art
        arguments:
          parameters:
          - name: prompt
            value: '{{{{ tasks.t1.result }}}}'
        dependencies: [t1]
      - name: t3
        template: image-resizing
        arguments:
          parameters:
          - name: width
            value: '{{workflow.parameters.width}}'
          - name: height
            value: 600
          - name: file
            value: '{{{{ tasks.t2.result }}}}'
        dependencies: [t2]
      - name: t4
        template: image-enhancement
        arguments:
          parameters:
          - name: file
            value: '{{{{ tasks.t3.result }}}}'
        dependencies: [t3]
      - name: t5
        template: image-enhancement
        arguments:
          parameters:
          - name: file
            value: '{{{{ tasks.t4.result }}}}'
        dependencies: [t4]
  - name: tti-charcoal-art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://example.com/tti_charcoal_art
      successCondition: response.statusCode == 200
  - name: image-resizing
    inputs:
      parameters:
      - name: width
      - name: height
      - name: file
    http:
      method: POST
      url: http://example.com/resize_image
      successCondition: response.statusCode == 200
  - name: image-enhancement
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://example.com/image_enhance
      successCondition: response.statusCode == 200
