apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: http-wf-
spec:
  arguments:
    parameters:
    - name: prompt
  entrypoint: main
  templates:
  - name: main
    inputs:
      parameters:
      - name: prompt
    dag:
      tasks:
      - name: t1
        template: tti_Sketching_Art
        arguments:
          parameters:
          - name: prompt
            value: '{{inputs.parameters.prompt}}'
        dependencies: []
      - name: t2
        template: image_to_pdf_conversion
        arguments:
          parameters:
          - name: file
            valueFrom:
              path: '{{tasks.t1.outputs.parameters.binary_image_file}}'
        dependencies: [t1]

  - name: tti_Sketching_Art
    inputs:
      parameters:
      - name: prompt
    http:
      method: POST
      url: http://external-service/tti_Sketching_Art
      body:
        prompt: '{{inputs.parameters.prompt}}'
      successCondition: response.statusCode == 200
    outputs:
      parameters:
      - name: binary_image_file
        valueFrom:
          jsonPath: response.data.file_path

  - name: image_to_pdf_conversion
    inputs:
      parameters:
      - name: file
    http:
      method: POST
      url: http://external-service/image_to_pdf_conversion
      body:
        file: '{{inputs.parameters.file}}'
      successCondition: response.statusCode == 200
    outputs:
      parameters:
      - name: pdf_file
        valueFrom:
          jsonPath: response.data.pdf_file
